---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("0a_report_functions.R")
source("0b_model_functions.R")
source("1a_data_prep.R")
```

# What is the MBBS?

A *Mini Breeding Bird Survey* (MBBS) is a small-scale version of the full [Breeding Bird Survey](https://www.pwrc.usgs.gov/bbs/) organized each year by the U.S. Fish and Wildlife Service throughout North America. An MBBS focuses on one county. Volunteers count birds seen or heard along randomly chosen routes on secondary roads. The objective is to determine the distribution of breeding birds in the county and to assess any year-to-year changes in their numbers. 

## History 

An annual MBBS began in Orange County (12 routes) in 1999, in Chatham County (14 routes) in 2000, and in Durham County (8 routes) in 2002. The number of routes in each county varies with the size of the county.

[Click here for the old MBBS site](old-mbbs/index.html), while content is moved to the new site.

### 2010 and onwards

In 2010 we began to use eBird.org to store the results of our surveys. Coordinated by the Cornell Laboratory of Ornithology and the National Audubon Society, eBird.org is now a widely used database for observations of birds worldwide.

By 2012 we had worked out kinks in this process and we covered all routes in Durham County and all but a few in Orange and Chatham Counties!

In 2015 we covered 26 of our 34 routes overall

* 6 (of 8) routes in Durham 
* 10 (of 12) in Orange
* 10 (of 14) in Chatham Counties.

Our goal is complete coverage in Durham and Orange and at least holding our own in Chatham!

## What we need now

### Participants to pick up vacant routes
 
* Qualifications
   * ability to identify our breeding birds (especially the  regular ones) by song or calls as well as by sight
   * interest in out-of-the-way parts of the area where we live
   * participation in  successive years (when possible)
   * and, last but not least, willingness to submit standard reports that can be used to evaluate trends in the numbers of our breeding birds


### County coordinators for Orange and Chatham Counties

* Qualifications
   * willingness to help in recruiting a few regularparticipants when needed (see above)
   * a few minutes each week (for several weeks in the summer) to encourage participants to run their routes and to enter their results in eBird in a timely way.

### Coordinators for additional Mini Breeding Birds Surveys in other counties, states, or elsewhere

To start a new MBBS, someone must select suitable routes (see the guidelines in our procedures), use Google Earth (or a GPS device) to obtain the coordinates of each starting location, spend a few hours with eBird to set up an account with the locations for the routes -- and, most important, recruit some partcipants! It is also important to download and save the eBird checklists with each year's results.

If you have questions, please contact <a href="mailto:pbailey@fhi.org">Patsy Bailey</a> (Durham County) or <a href="mailto:rhwiley@email.unc.edu">Haven Wiley</a>.
