# For more info about this config, see:
# https://docs.netlify.com/configure-builds/file-based-configuration/
# 
# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.

# A basic redirect rule
[[redirects]]
  from = "/*"
  to = "/"