#------------------------------------------------------------------------------#
#  Build Route.elm
#------------------------------------------------------------------------------#

library(glue)
library(dplyr)
library(mbbs)
library(yaml)
library(purrr)

#### Read Route YAML data
route_info <-
  purrr::map_dfr(
    .x = list.files("routes", pattern = "\\.yaml", full.names = TRUE),
    .f = ~ read_yaml(.x) |> purrr::flatten()
  ) |>
  mutate(
    start = trimws(start),
    county = stringr::str_to_title(county)
  )

#### Elm Code Generation

route_file <- '
{{- 
Elm code generated by Route-build.R
This file should not be modified except by code formatters.
-}}
module Data.Route exposing (..) \n

import Data.County exposing (..)
import String exposing (..)

type alias Route =
    {{ county : County
    , number : Int
    , start : String
    , name : String
    , directions : String
    , mapid : String
    , maplat : Float
    , maplon : Float
    }}

routeToString : Route -> String
routeToString x =
    countyToString x.county ++ " " ++ fromInt x.number

routeToTitle : Route -> String
routeToTitle x =
    countyToTitle x.county ++ " " ++ fromInt x.number

stringToRoute : String -> Maybe Route
stringToRoute x =
    let
        res =
            split " " x

        cnty =
            List.head res |> Maybe.andThen stringToCounty

        num =
            List.head (List.reverse res) |> Maybe.andThen toInt
    in
    case ( cnty, num ) of
        ( Just c, Just i ) ->
           List.head (List.filter (\\r -> r.county == c && r.number == i) allRoutes)
 
        _ ->
            Nothing

-- All Routes
allRoutes : List Route
allRoutes = [ { route_records } ] \n
'

route_template <- '
  {{  county = { county }
    , number = { route_num } 
    , start = "{ start }"
    , name  = "{ name }"
    , directions = "{ directions }"
    , mapid = "{ mid }"
    , maplat = { lat }
    , maplon = { lon }
    }}
'

route_records <-
 glue_data(.x = route_info, route_template) |>
 glue_collapse(sep = "\n , ")

glue(
    route_file,
    route_records = route_records
) |>
cat(file = "src/Data/Route.elm")
