---
subtitle: "DRAFT: for discussion only"
output:
  html_document:
    toc: true
    toc_depth: 2
    includes:
      in_header: vega-imports.html
editor_options: 
  chunk_output_type: console
---

```{=html}
<script src="./js/speciesTrendSpec.js"></script>
```

```{r trend_setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

tot_sp_cnt <- length(unique(pre_dt$common_name))
ana_sp_cnt <- length(unique(analysis_dt_grouped$common_name))
species <- unique(analysis_dt_grouped$common_name)
start_year <- min(analysis_dt_grouped$year, na.rm = TRUE)
end_year <- max(analysis_dt_grouped$year, na.rm = TRUE)
```

## Trends by Species

From `r start_year`-`r end_year`, 
`r tot_sp_cnt` different species were observed. 
For these analyses, 
only species counted in at least three years were included, 
leaving `r ana_sp_cnt` species for analysis of trends.

```{r results_data}
table_dt <- mbbs_results %>%
  select(common_name, sparkline, rate, details, significant)
```

```{r}
species_table <- function(table_data, 
                          details_column,
                          width,
                          colnames){
  tab <-
  DT::datatable(
    cbind(" " = "&oplus;", table_data),
    colnames  = colnames,
    width  = width,
    escape = FALSE,
    options = list(
      paging     = FALSE,
      bInfo      = FALSE,
      columnDefs = list(
        list(
            targets = c(3,4,5)
          , className = "text-center"),
        list(
            targets = c(2, details_column, 6)
          , searchable = TRUE),
        list(
            targets = c(0, details_column, 6)
          , visible = FALSE),
        list(
            orderable = FALSE
          , className = "details-control"
          , targets = c(1, details_column)
        )
      )
    ),
    callback = DT::JS(sprintf("
    table.column(1).nodes().to$().css({cursor: 'pointer'});
    
    var format = function(d) {
      return d[%s];
    };
    
    table.on('click', 'td.details-control', function() {
      var td = $(this), row = table.row(td.closest('tr'));
      if (row.child.isShown()) {
        row.child.hide();
        td.html('&oplus;');
      } else {
        row.child(format(row.data())).show();
        td.html('&CircleMinus;');
      }
    });
    
    /*
    $('ul').on( 'click', 'a.localConcern', function () {
    table
        .columns( 6 )
        .search(  true )
        .draw();
    });
    */
    
    $('ul').on( 'click', 'a.sigTrends', function () {
    table
        .columns( 6 )
        .search(  true )
        .draw();
    });
    
    $('ul').on('click', 'a.all', function() {
      table
        .columns( )
        .search( '' )
        .draw();
      });
    
    ", details_column)
    )
  )

  # Add sparkline JS dependency
  tab$dependencies <-
    append(tab$dependencies, htmlwidgets:::getDependency("sparkline"))
  tab
}
```

```{r}
library(htmltools)
tags$ul(
  tags$li(
    class = "btn",
    tags$a(href = "#", class = "all", "All Species")
  ),
  tags$li(
    class = "btn",
    tags$a(href = "#", class = "sigTrends", "Significant Trends")
  )
)

```


```{r show_table, echo=FALSE}
species_table(
  table_data = table_dt,
  details_column = 5,
  width    = NULL,
  colnames = c("", "", "Common name", "Trend", "Rate of Change", "", "")
)
```


```{r child = "_methods.Rmd"}
```

```{r child = "_past_results.Rmd"}
```
