{- 
Elm code generated by Route-build.R
This file should not be modified except by code formatters.
-}
module Data.Route exposing (..) 


import Data.County exposing (..)
import String exposing (..)

type alias Route =
    { county : County
    , number : Int
    , start : String
    , name : String
    , directions : String
    , mapid : String
    , maplat : Float
    , maplon : Float
    }

routeToString : Route -> String
routeToString x =
    countyToString x.county ++ " " ++ fromInt x.number

routeToTitle : Route -> String
routeToTitle x =
    countyToTitle x.county ++ " " ++ fromInt x.number

stringToRoute : String -> Maybe Route
stringToRoute x =
    let
        res =
            split " " x

        cnty =
            List.head res |> Maybe.andThen stringToCounty

        num =
            List.head (List.reverse res) |> Maybe.andThen toInt
    in
    case ( cnty, num ) of
        ( Just c, Just i ) ->
           List.head (List.filter (\r -> r.county == c && r.number == i) allRoutes)
 
        _ ->
            Nothing

-- All Routes
allRoutes : List Route
allRoutes = [ {  county = Chatham
  , number = 1 
  , start = "Russell Chapel Road (County Road 1520) 1.4 miles west of US 15-50 (turn left 3.1 miles north of Pittsboro center)."
  , name  = "Russell Chapel Road (north-central Chatham County)"
  , directions = "go east on Russell Chapel Road 1.4 miles to US 15-501 turn left on US 15-501, cross the Haw River and turn left on Moore Mountain Road (CR 1524), proceed 1.9 miles to River Road (CR1525), turn left on River Road and go 0.6 miles, turn right on Manns Chapel Road (CR 1532), and continue until your have completed 20 stops (near US 15-501)."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.8073520714585
  , maplon = -79.1568515583886
  }
 , {  county = Chatham
  , number = 2 
  , start = "Old Hope Valley Farm Road (CR 1728) on Mason Neck at gate 1.0 miles south of Farrington Mill Road near the county line (as far south as you can go)"
  , name  = "Mason Neck (northeastern Chatham County)"
  , directions = "go north on Old Hope Valley Farm Road to Farrington Mill Road, turn left on Farrington Mill Road (CR 1109) and continue 1.9 miles to Mount Carmel Church Road (CR 1008), turn left and proceed southward about 2.3 miles, turn right on Lystra Road and after 1.0 miles turn left on Jack Bennett Road (CR 1717), continue all the way to US 15-501, turn left on US 15-501 for about 0.7 miles, turn right on Andrews Store Road (CR 1528) and continue until you have completed 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.8797466882081
  , maplon = -78.9570607975023
  }
 , {  county = Chatham
  , number = 3 
  , start = "Farrington Road 1.1 miles north of the junction with Old US 1  (Hillsborough Street) at Bonsal on the county line."
  , name  = "Bonsal Crossroads (southeastern Chatham County)"
  , directions = "go south on Farrington Road (CR 1008) to Old US 1,  turn right and continue to Merry Oaks center, turn left on Christian Church Road (CR 1912), continue 1.6 miles and turn right on Moncure Flat Road (CR 1924), continue over 3 miles all the way to NC 42, turn left on NC 42 through Brickhaven until you have completed 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.62826513
  , maplon = -78.99959131
  }
 , {  county = Chatham
  , number = 4 
  , start = "Henry Oldham Road (CR 2142) 0.7 miles northeast of junction with Lukes Church Road (CR 2135) north of Gulf on the Deep River."
  , name  = "Henry Oldham Road (north of Gulf) (south-central Chatham County)"
  , directions = "go south on Henry Oldham Road (CR 2142), turn right on Lukes Church Road (CR 2135), continue about 3 miles (across US 421 bypass) to Goldston center, turn right on US 421 and then immediately turn right again on Pittsboro Road (CR 1010), in about 1 mile (back across US 421 bypass) turn left on Verne Phillips Road (CR 2189), after 1.4 miles turn left on Campbell Road (CR 2129), in 0.5 miles turn right on Mark Willett Road (CR 2181) and go 1.3 miles to NC 902, turn right on NC 902 and go 0.7 miles before turning left on Ralph Moore Road (CR 2178), after 2.2 miles turn right on Dean Beavers Road (CR 2180) and continue until you have completed 20 stops (assuming you are not lost!)."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.61871977
  , maplon = -79.32448757
  }
 , {  county = Chatham
  , number = 5 
  , start = "Joe Brown Road (CR 1150) 0.5 miles south of junction with Oakley Church Road (CR 1151)."
  , name  = "Joe Brown Road about 3.5 miles south of Siler City (southwestern Chatham County)"
  , directions = "go south and east on Joe Brown Road to Siler City-Glendon Road (CR 1100), turn right and go 1.3 miles to Bonlee-Bennett Road (CR 1005), turn left and proceed 1.1 miles to Palmer Church Road (CR 1136), turn right and continue to and through Providence Church Rd. After Providence Church Rd., Palmer Church Rd. become Herb Beavers Rd. Follow it all the way (4.4 miles) to a T-junction with Edwards Hill Church Rd (CR 1141), turn right and proceed 4.3 miles south. When this road crosses NC 902, it becomes Tom Hancock Rd.  Follow Tom Hancock Rd. to Vander-Oldham Road (CR 2312).  If you haven’t completed 20 stops, then turn left and continue until you have completed 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.61241167
  , maplon = -79.48801461
  }
 , {  county = Chatham
  , number = 6 
  , start = "Silk Hope-Liberty Road (CR 1346) 0.4 miles east of junction with Pete Thomas Road (CR 1353) about 5 miles due north of Siler City."
  , name  = "Silk Hope-Liberty Road (northwestern Chatham County)"
  , directions = "go west on Silk Hope-Liberty Road a short way and turn right on Sam Lowe Road (CR 1353) (Pete Thomas Road in DeLorme Atlas), proceed north 1.5 miles almost to the county line and turn right on Flint Ridge Road (CR 1351), continue east and southeast all the way back to Silk Hope-Liberty Road (CR 1346), turn left here and continue through Silk Hope, until you have completed 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.81794501
  , maplon = -79.44453999
  }
 , {  county = Chatham
  , number = 7 
  , start = "Rives Chapel Road 1.7 miles south of US 64 about 5 miles east of Siler City."
  , name  = "Rives Chapel Road (CR 2170) (central Chatham County)"
  , directions = "go south on Rives Chapel Road about 1.0 mile to Carolina Hill Road (CR 2168), turn left and continue 2.6 miles to Pleasant Hill Church Road (CR 1506), turn left and in less than 0.5 miles turn right on Jay Shambley Road (CR 2167), continue 3.0 miles to Hadley Mill Road (2165), turn right and proceed 0.7 miles to Elmer Keck Road (CR 2166), turn left and go 1.1 miles to Alex Cockman Road (CR 2163), turn right and go 1.0 miles to Alston Chapel Road (CR 2159), turn left and continue until you have completed 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.71150935
  , maplon = -79.33345279
  }
 , {  county = Chatham
  , number = 8 
  , start = "Mt. Olive Church Road (County Road 1520) 2.9 miles south of Terrells just south of a chapel marked on the county road map (this location is about 5.4 miles north of US 64 on the west side of Pittsboro – take Old NC 87 which becomes Mt. Olive Church Road about 3.3 miles north of Pittsboro)."
  , name  = "Mount Olive Church Road (Terrells) (north-central Chatham County)"
  , directions = "go north on Mt. Olive Church Road all the way to Terrells, turn left on Chicken Bridge Road (CR 1545) and after 0.9 miles keep right on Mann Road (CR 1546) until you reach NC 87, turn left on NC 87 and after 0.7 miles turn right on Big Meadow Road (CR 1549), continue about 4.7 miles (0.4 miles past Van Thomas Road), then turn right on Otis Johnson Road (CR 1552) and continue until you have competed 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.81208045
  , maplon = -79.27649174
  }
 , {  county = Chatham
  , number = 9 
  , start = "Mount Gilead Church Road (CR 1700) 0.7 miles south of US 15-501 northeast of Bynum."
  , name  = "Mount Gilead Church Road (CR 1700) (northeastern Chatham County)"
  , directions = "go south on Mount Gilead Church Road (CR 1700) all the way to Griffins Crossroads, continue straight across US 64 and continue straight into Vista Point Recreation Area (Jordan Lake) as far as possible. At this point, backtrack to the junction with Seaforth Road (CR1941) without making any stops. Turn southwest (to the left as you return from Vista Point) on Seaforth Road (CR 1941) and resume making stops as far as you can go. Once again, backtrack to the junction of Seaforth Road and North Pea Ridge Road without making stops. Then proceed northeast on Seaforth Road (straight ahead this time) and resume making stops. Continue about 2.4 miles to US 64, turn right (east) on US 64 and continue until you have made 20 stops. If stops are not safe on US 64, continue across the lake and turn right on Farrington Road (CR 1008) and proceed south toward Ebenezer Church Recreation Area until you have completed your stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.75209766
  , maplon = -79.05269657
  }
 , {  county = Chatham
  , number = 10 
  , start = "Gum Springs Church Road (CR 1939) at the junction with Clark Poe Road (CR 1931) – also 1.8 miles northeast of the junction with Moncure-Pittsboro Road (CR 1012) – about 5 miles southeast of Pittsboro."
  , name  = "Gum Springs Church Road (southeastern Chatham County)"
  , directions = "go southwest on Gum Springs Church Road (CR 1939) to Moncure-Pittsboro Road (CR 1012), turn right and continue all the way to US 15-501/NC 87, turn right and proceed to Pittsboro center, go around the courthouse and head west on US 64, after about 0.6 miles turn right on NC 87 and soon thereafter branch right on Old NC 87 (CR 1516), continue until you have competed 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.70406138
  , maplon = -79.16932849
  }
 , {  county = Chatham
  , number = 11 
  , start = "Reno Sharps Store Road (CR 2188) 1.0 mile south of Goldston-Pittsboro Road (CR 1010) just over 2 miles east of Goldston."
  , name  = "Reno Sharps Store Road (south-central Chatham County)"
  , directions = "go north on Reno Sharps Store Road (CR 2188) to Goldston-Pittsboro Road (CR 1010), turn right and continue about 3.8 miles until you cross the Rocky River, soon afterward turn right on Holly Ridge Road (CR 2158), after 1.0 mile turn right on Pete Roberson Road (CR 2157), continue 1.6 miles and turn left on Chatham Church Road (CR 1953), after 1.8 miles turn left on Old Sanford Road and then in 0.2 miles turn right on Charlie Brooks Road (CR 1969), cross US 15-501 and continue on Charlie Brooks Road until you have made 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.64743656
  , maplon = -79.24298705
  }
 , {  county = Chatham
  , number = 12 
  , start = "Sunny Slope Road (CR 1150) 0.8 miles east of Airport Road (CR 1100) about 3.5 miles north of Bennett and Bonlee-Bennett Road."
  , name  = "Sunny Slope Road (southwestern Chatham County)"
  , directions = "go south and east on Sunny Slope Road to Devil’s Tramping Ground Road (CR 1100), turn left and proceed 1.0 mile to Bonlee-Bennett Road (CR1005), turn right and go 2.1 miles to Siler City-Glendon Road (CR 1006), turn left and go 1.2 miles (this stretch repeats part of Route 5 but your stops are not likely to fall in the same places), turn right on Mount Vernon Spring Road (CR 1134), continue all the way to Mount Vernon Springs center, cross Old US 421 (the road becomes Foust Road) and immediately turn right on Buck Gunter Road (CR 2119) continue eastward straight across US 421 until you have completed 20 stops (if necessary turn left on Ike Brooks Road CR 2120)."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.64709314
  , maplon = -79.47711654
  }
 , {  county = Chatham
  , number = 13 
  , start = "Coleridge Road (CR1102) (Blood Run Road in DeLorme Atlas) at the junction with Moons Chapel Road near the county line west of Siler City (6 miles west of the first stoplight in Siler City)"
  , name  = "Coleridge Road (northwestern Chatham County)"
  , directions = "go east on Coleridge Road (CR 1102) to Old US 64 (now CR 1107) west of Siler City, turn right and proceed to the center of Siler City  on West Third Street after a bend to the left), turn left on US 421 (North Second Avenue), after two blocks turn right onto Martin Luther King Boulevard, follow a bend to the left, cross US 64, and then head northeast out of Siler City on Snow Camp Road (CR 1004), after about 2.5 miles turn right on Jesse Bridges Road (CR 1332) and continue until you have made 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.74211072
  , maplon = -79.49363413
  }
 , {  county = Chatham
  , number = 14 
  , start = "south end of the causeway over White Oak Creek on Farrington Road (CR 1008) about 0.9 miles north of US 64."
  , name  = "Whiteoak Creek (northeastern Chatham County)"
  , directions = "go north on Farrington Road a little over 3.0 miles to Martha’s Chapel Road, turn right and continue to NC 751, turn left and go 1.1 miles to Mt. Pisgah Church Road (CR 1736), turn right and proceed 2.0 miles to a T-junction with New Hope Church Road, turn right and continue until you have completed 20 stops (hopefully before you reach the county line!)."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.78304351
  , maplon = -78.9969488
  }
 , {  county = Durham
  , number = 1 
  , start = "intersection of South Lowell Rd (SR 1461) and Guess Rd (SR 1003)."
  , name  = "South Lowell Road NE (northwestern Durham County)"
  , directions = "go north on South Lowell. Just after crossing Little River, turn left onto South Lowell, which becomes SR 1464. Continue to 501, skipping the 4-lane stretch, and turn left onto 501. Turn right onto Moore’s Road and right again onto a gravel road that has no official state road sign. On the left you should immediately see a sign that says Hill Forest and SR 1614. On the right is a DOT diamond-shaped sign that reads “Road subject to flooding”. Go to the end of the road, crossing the Flat River and passing through NC State Univ. forest. Turn left onto Wilkens Road and left again onto Hampton (SR 1603). Turn right onto Red Mountain Road (SR 1471) and continue until you have completed 10 miles."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.18873604
  , maplon = -78.91688497
  }
 , {  county = Durham
  , number = 2 
  , start = "junction of Stagville Road (SR 1615) and Old Oxford Highway (SR 1626)."
  , name  = "Stagville Road NW (northeastern Durham County)"
  , directions = "drive northwest on Stagville to its end. Turn left onto John Jones Road (SR 1618) and continue to Ball Road (SR 1617) where you turn right, crossing Bahama Road and railroad tracks. Turn left onto Quail Roost Road (SR 1615) and continue until you finish 10 miles. If more road is necessary, turn right on 501 and left onto Conference Road (SR 1468)."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.16490289
  , maplon = -78.88645799
  }
 , {  county = Durham
  , number = 3 
  , start = "intersection of Broad Street and Club Boulevard."
  , name  = "Broad Street NW (central western Durham County)"
  , directions = "go north on Broad Street turning left onto Guess Road. Turn left onto Carver Street. Go about 1.5 miles to Rose of Sharon Road and turn left and right onto Cole Mill Road. Follow Cole Mill Road, cross the Eno River and turn right onto Umstead Road (SR 1449). Follow Umstead to Guess Road and turn left onto Guess Road until you have completed 10 miles."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.06944472
  , maplon = -78.9342455
  }
 , {  county = Durham
  , number = 4 
  , start = "junction of Goodwin (SR 1640) and 501, across from Northern High School."
  , name  = "Goodwin Road SW (central Durham County)"
  , directions = "go east on Goodwin until Infinity Road (SR 1639), turn left and continue to the end of Infinity. Turn right onto Snow Hill (SR 1631). This takes you to Old Oxford Highway (SR 1004) where you should turn left. You will cross railroad tracks and an arm of Falls Lake. Continue until you can bear right on Teknika Parkway. Turn right onto Red Mill Road (SR 1632). Go as far as necessary until you have completed 10 miles. If necessary, turn left on East Geer Street."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.07832451
  , maplon = -78.87664049
  }
 , {  county = Durham
  , number = 5 
  , start = "intersection of Farrington Mill Road (SR 1109) and Kepley Road (SR 1108) – Kepley is about 0.5 miles south of Barbee Chapel Road."
  , name  = "Farrington Mill Road NW (southwestern Durham County)"
  , directions = "go north on Farrington Mill, turn right onto Farrington Road (SR 1110) and cross Hwy 54. Continue north, passing I-40. At Old Chapel Hill Road, turn right and cross New Hope Creek, turning right onto Chapel Hill Road (do not continue on University Drive). When Chapel Hill Road meets University Drive, turn right and immediately turn left onto Academy Road (751). Stay on Academy and at the major intersection and stoplight near the old university president's house, veer right onto Duke University Road and continue as far as needed to complete 10 miles."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.95855933
  , maplon = -78.98165369
  }
 , {  county = Durham
  , number = 6 
  , start = "county line (between Durham and Wake) on Slatter Road (SR 1974) less than 0.2 miles east of I-540."
  , name  = "Slater Road NW (Cornwallis Road) (south central Durham County)"
  , directions = "follow Slatter to Emperor Boulevard where you turn right. Turn left at Page Road and right at the stoplight of 'Imperial Corners' (still on Page Rd.). Turn right on South Miami. At about the 3-mile mark, turn left onto Cornwallis Rd. Stay on Cornwallis until 10 miles have been completed, skipping as necessary 4-lane stretches. If you skip a lot, note that Cornwallis Road does a jag at Chapel Hill Road at Hardee's."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.93236828
  , maplon = -78.88585707
  }
 , {  county = Durham
  , number = 7 
  , start = "intersection of Mineral Springs Road (SR 1881) and Sherron Road."
  , name  = "Sherron Road NE (central eastern Durham County) (formerly Mineral Springs Road NE)"
  , directions = "go northeast on Sherron for 3.0 miles. Turn right on Route 98 (Old Wake Forest Hwy). Go 0.7 miles (skip this section for birding) and turn left on Baptist Road. Go 1.9 miles and turn right on South View Road (SR 1809); it's gravel. Cross Rt. 98, stay on South View. Turn left on Kemp Road (SR 1902), right on Carpenter Pond Rd (SR 1901). Continue until 10 miles are completed."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.96972237
  , maplon = -78.7886218
  }
 , {  county = Durham
  , number = 8 
  , start = "intersection of Olive Branch Road and Leesville Road."
  , name  = "Olive Branch Road NW (southeastern Durham County)"
  , directions = "go northwest on Olive Branch Road (SR 1905) for 3.8 miles to Wake Forest Road (NC 98). Turn left onto 98 for 0.4 miles (skip this section for birding) and turn right onto Patterson Road (SR 1811) and an immediate left onto Stallings (SR 1814), which becomes Fletcher's Chapel Road (SR 1882) and go north until Cheek Road. Cross Cheek Road and Fletcher's Chapel Rd. becomes Burton Road. Follow Burton north until crossroads with Gorman. At Gorman, turn right onto Geer Street. Continue until you finish."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.00221376
  , maplon = -78.79854823
  }
 , {  county = Orange
  , number = 1 
  , start = "northernmost point of Wade Loop, 1.5 miles NE of Carr (crossroads on NC 49) and 1 mile north of the junction with NC 49."
  , name  = "Wade Loop (northwestern Orange County)"
  , directions = "go south on the eastern arm of Wade Loop to NC 49, turn left on NC 49 for a short distance and then right on McCullough Road, continue east about 1 mile to NC 86 (short jog right and left to cross McDade Store Rd), turn right on NC 86 for a short distance and then right on Efland Cedar Grove Road (the second right turn), continue south on this road through Cedar Grove (crossroads), about 1.5 miles south of Cedar Grove turn left on Highland Farm Road, in about 1.5 miles turn left on Kenion Road"
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.18883853
  , maplon = -79.20235142
  }
 , {  county = Orange
  , number = 2 
  , start = "Schley Road 0.7 miles east of Walnut Grove Church Road (about 5 miles north of Hillsborough center)"
  , name  = "Schley Road (northeastern Orange County)"
  , directions = "go west to Walnut Grove Church Road,  urn right and continue about 4 miles to Laws Store Road, turn right on Laws Store Road and then left on Brown Road, continue about 3 miles to NC 157, turn left on NC 157 for a short distance and then right on Berry Road, in about one-half mile turn right on Gary Road."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.20275288
  , maplon = -79.08106333
  }
 , {  county = Orange
  , number = 3 
  , start = "junction of Efland Cedar Grove Road and Harmony Church Road (5 miles NW of Hillsborough center)"
  , name  = "Harmony Church Road (central western Orange County)"
  , directions = "go west on Harmony Church Road about 1 mile, turn left on Ira Road and continue about 2 miles to Lebanon Road West, turn right on Lebanon Road West for about one-half mile, turn left on Frazier Road (on the east side of Mebane) and continue to US 70, turn right on US 70 and then left on Buckhorn Road, cross I 40 and proceed to the crossroads just south of I 40, turn right on Ten Road and then almost immediately turn left on Hebron Church Road, continue on Hebron Church Road about 3 miles to Mebane-Oaks Road, turn left on Mebane-Oaks Road."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.08380007
  , maplon = -79.23191846
  }
 , {  county = Orange
  , number = 4 
  , start = "Town Hall in Hillsborough (Churton Street at Corbin Street)"
  , name  = "Town Hall (central eastern Orange County)"
  , directions = "east on Corbin one block, south to Margareet Street (one short block past King Street), west to Churton (NC 86), south on Churton across the Eno River, left following NC 86 at the traffic light, right following NC 86 across I 40 (there is no way around this stretch along NC 86), take the first left on Old NC Highway 10, continue all the way to Cornwallis Road  (first turn after the underpass under the railroad), turn right on Cornwallis Road  (if you need to room for the last count or two,  turn right on Kerley Road just before reaching the county line)"
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.05007821
  , maplon = -79.06132913
  }
 , {  county = Orange
  , number = 5 
  , start = "Arthur Minnis Road 0.7 miles east of Dodson's Crossroads North"
  , name  = "Arthur Minnis Road (southwestern Orange County)"
  , directions = "west on Minnis Road to Dodson's Crossroads North, turn left on Dodson's Crossroads North, at the crossroads turn right on Dairy Land Road, at Orange Grove crossroads turn left on Orange Grove Road, after about 1 mile turn right on Teer Road, after about 2 miles turn left on Stanford Road, cross NC 54 (on the south sides of NC 54 the road is named Gold Mine Road), after about one mile turn right on Morrow Mill Road, after about one mile turn left on Willikan Road"
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.96986827
  , maplon = -79.20357367
  }
 , {  county = Orange
  , number = 6 
  , start = "Mount Sinai Church Road at Friends School Road"
  , name  = "Friends School Road (southeastern Orange County)"
  , directions = "go west on Mt. Sinai Church Road, after more than one mile turn left on Turkey Farm Road, after almost two miles turn right on Whitfield Road, at the end of Whitfield Road turn left over I 40 and then turn right immediately on Eubanks Road, continue about 1.5 miles and turn left on Rogers Road, after more than one mile turn right on Homestead Road, at Calvander turn left on Hillsborough Road, in less than one mile turn right (actually angle right) on Old Fayetteville Road (cross NC 54 and continue on Old Fayetteville Road if you need room for the last count or two)"
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.97091485
  , maplon = -79.08001166
  }
 , {  county = Orange
  , number = 7 
  , start = "junction of Mill Creek Road and High Rock Road (2.5 miles north of Mebane center)"
  , name  = "Mill Creek Road (northwestern Orange County)"
  , directions = "go north on Mill Creek Road almost 4 miles to Carr Store Road, turn right on Carr Store Road, cross Eno River and soon turn left on Lee's Chapel Road, proceed less than one mile and turn left on Jakley Road, follow Jakley Road about one mile to McDade Store Road, turn right on McDade Store Road and continue through McDade crossroads  (cross Efland Cedar Grove Road), continue on McDAde Store Road to NC 86, cross NC 86 and continue on Hurdle Mills Road."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.18013969
  , maplon = -79.19174574
  }
 , {  county = Orange
  , number = 8 
  , start = "junction of Guess Road and Bromley Road  just inside the Orange County line"
  , name  = "Guess Road (northeastern Orange County)"
  , directions = "head north on Guess Road for about 3.5 miles, turn left on Green Riley Road, proceed for a little over one mile to NC 57, turn left on NC 57 and then almost immediately turn right on Little River Church Road, follow L. R. Church Road just over a mile and turn right on Hawkins Road East, go north and then west on Hawkins Road East almost three and a half miles to Walnut Grove Church Road, cross W. G. Church Road and continue on Hawkins Road East over a mile to Wilkerson Road, turn right on Wilkerson Road and continue far enough to finish 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.1832561
  , maplon = -79.05606409
  }
 , {  county = Orange
  , number = 9 
  , start = "junction of Arthur Minnis Road and Borland Road  (less than a mile west of Old NC 86 about 3.5 miles north of Calvander)"
  , name  = "Borland Road (central western Orange County)"
  , directions = "go west on Borland Road about 4.5 miles (cross Orange Grove Road and Cane Creek) to Chestnut Ridge Road, turn left on Chestnut Ridge Road and proceed about 2 miles to Buckhorn Road, turn right (north) on Buckhorn Road and continue through Buckhorn crossroads far enough to finish 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.02070336
  , maplon = -79.18489641
  }
 , {  county = Orange
  , number = 10 
  , start = "junction of New Hope Church Road and Old NC 86 about 3.5 miles north of Calvander"
  , name  = "New Hope Church Road (central eastern Orange County)"
  , directions = "proceed northeast along New Hope Church Road over 4 miles (cross I-40 and NC 86) to Old NC 10, turn left on Old NC 10 and proceed about 1.5 miles (THIS 1.5 MILES IS ALREADY INCLUDED IN ROUTE 4 ABOVE --  DO NOT INCLUDE THIS 1.5 MILES IN THE MILEAGE FOR THE PRESENT ROUTE), turn right on Lawrence Road, proceed just over 3 miles (cross I-85, US 70 Business, US 70 Bypass, and Eno River) to St. Mary's Road, turn right on St. Mary's Road and proceed about a half mile to New Sharon Church Road, turn left on New Sharon Church Road and continue far enough to finish 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 36.06490022
  , maplon = -79.12555065
  }
 , {  county = Orange
  , number = 11 
  , start = "Damascus Church Road at a point 2.2 miles west of Smith Level Road (the southernmost point on Damascus Church Road)"
  , name  = "Damascus Church Road (southwestern Orange County)"
  , directions = "proceed northwest on Damascus Church Road to Jones Ferry Road, turn left on Jones Ferry Road and then immediately turn right on Bowden Road, follow Bowden Road to Old Greensboro Road, turn left and proceed about 1.5 miles to Carl Durham Road, turn right on Carl Durham Road and continue to NC 54 in White Cross, turn left on NC 54 and then immediately turn right on Dodson's Crossroads South, continue more than 3 miles to Dodson's Crossroads itself, turn right on Dairy Land Road and continue far enough to finish 20 stops."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.91733903
  , maplon = -79.15507967
  }
 , {  county = Orange
  , number = 12 
  , start = "junction of Mt. Carmel Church Road and Mangum Court just north of the county line"
  , name  = "Mt. Carmel Church Road (southeastern Orange County)"
  , directions = "proceed northwest on Mt. Carmel Church Road over 2.5 miles to US 15-501, cross US 15-501 and continue on Culbreth Road to Smith Level Road, turn right on Smith Level Road and proceed into Carrboro (passing under NC 54 where the name of the road changes to South Greensboro Street), at Main Street in Carrboro continue north on Greensboro Road (past Fitch Lumber and Southern States) all the way to the merger with Hillsborough Road, continue on Hillsborough Road less than 1.5 miles to Old Fayetteville Road, continue northwest about 0.7 miles to Calvander crossroads  (THIS SECTION FROM OLD FAYETTEVILLE ROAD TO CALVANDER IS INCLUDED IN ROUTE 6 ABOVE), at Calvander turn left on Dairyland Road, continue for more than 0.5 miles and turn right on Union Grove Church Road, continue north on Union Grove Church Road far enough to complete 20 stops  (at Albert Road, keep right to stay on Union Grove Church Road)."
  , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
  , maplat = 35.93125278
  , maplon = -79.09143543
  } ] 
