{-
   Elm code generated by Route-build.R
   This file should not be modified except by code formatters.
-}


module Data.Route exposing (..)

import Data.County exposing (..)
import String exposing (..)


type alias Route =
    { county : County
    , number : Int
    , start : String
    , name : String
    , directions : String
    , mapid : String
    , maplat : Float
    , maplon : Float
    }


routeToString : Route -> String
routeToString x =
    countyToString x.county ++ " " ++ fromInt x.number


routeToTitle : Route -> String
routeToTitle x =
    countyToTitle x.county ++ " " ++ fromInt x.number


stringToRoute : String -> Maybe Route
stringToRoute x =
    let
        res =
            split " " x

        cnty =
            List.head res |> Maybe.andThen stringToCounty

        num =
            List.head (List.reverse res) |> Maybe.andThen toInt
    in
    case ( cnty, num ) of
        ( Just c, Just i ) ->
            List.head (List.filter (\r -> r.county == c && r.number == i) allRoutes)

        _ ->
            Nothing



-- All Routes


allRoutes : List Route
allRoutes =
    [ { county = Chatham
      , number = 1
      , start = "Russell Chapel Road (County Road 1520) 1.4 miles west of US 15-50 (turn left 3.1 miles north of Pittsboro center)."
      , name = "Russell Chapel Road (north-central Chatham County)"
      , directions = "go east on Russell Chapel Road 1.4 miles to US 15-501 turn left on US 15-501, cross the Haw River and turn left on Moore Mountain Road (CR 1524), proceed 1.9 miles to River Road (CR1525), turn left on River Road and go 0.6 miles, turn right on Manns Chapel Road (CR 1532), and continue until your have completed 20 stops (near US 15-501)."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.8073520714585
      , maplon = -79.1568515583886
      }
    , { county = Chatham
      , number = 2
      , start = "Old Hope Valley Farm Road (CR 1728) on Mason Neck at gate 1.0 miles south of Farrington Mill Road near the county line (as far south as you can go)"
      , name = "Mason Neck (northeastern Chatham County)"
      , directions = "go north on Old Hope Valley Farm Road to Farrington Mill Road, turn left on Farrington Mill Road (CR 1109) and continue 1.9 miles to Mount Carmel Church Road (CR 1008), turn left and proceed southward about 2.3 miles, turn right on Lystra Road and after 1.0 miles turn left on Jack Bennett Road (CR 1717), continue all the way to US 15-501, turn left on US 15-501 for about 0.7 miles, turn right on Andrews Store Road (CR 1528) and continue until you have completed 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.8797466882081
      , maplon = -78.9570607975023
      }
    , { county = Chatham
      , number = 3
      , start = "Farrington Road 1.1 miles north of the junction with Old US 1  (Hillsborough Street) at Bonsal on the county line."
      , name = "Bonsal Crossroads (southeastern Chatham County)"
      , directions = "go south on Farrington Road (CR 1008) to Old US 1,  turn right and continue to Merry Oaks center, turn left on Christian Church Road (CR 1912), continue 1.6 miles and turn right on Moncure Flat Road (CR 1924), continue over 3 miles all the way to NC 42, turn left on NC 42 through Brickhaven until you have completed 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.62826513
      , maplon = -78.99959131
      }
    , { county = Chatham
      , number = 4
      , start = "Henry Oldham Road (CR 2142) 0.7 miles northeast of junction with Lukes Church Road (CR 2135) north of Gulf on the Deep River."
      , name = "Henry Oldham Road (north of Gulf) (south-central Chatham County)"
      , directions = "go south on Henry Oldham Road (CR 2142), turn right on Lukes Church Road (CR 2135), continue about 3 miles (across US 421 bypass) to Goldston center, turn right on US 421 and then immediately turn right again on Pittsboro Road (CR 1010), in about 1 mile (back across US 421 bypass) turn left on Verne Phillips Road (CR 2189), after 1.4 miles turn left on Campbell Road (CR 2129), in 0.5 miles turn right on Mark Willett Road (CR 2181) and go 1.3 miles to NC 902, turn right on NC 902 and go 0.7 miles before turning left on Ralph Moore Road (CR 2178), after 2.2 miles turn right on Dean Beavers Road (CR 2180) and continue until you have completed 20 stops (assuming you are not lost!)."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.61871977
      , maplon = -79.32448757
      }
    , { county = Chatham
      , number = 5
      , start = "Joe Brown Road (CR 1150) 0.5 miles south of junction with Oakley Church Road (CR 1151)."
      , name = "Joe Brown Road about 3.5 miles south of Siler City (southwestern Chatham County)"
      , directions = "go south and east on Joe Brown Road to Siler City-Glendon Road (CR 1100), turn right and go 1.3 miles to Bonlee-Bennett Road (CR 1005), turn left and proceed 1.1 miles to Palmer Church Road (CR 1136), turn right and continue to and through Providence Church Rd. After Providence Church Rd., Palmer Church Rd. become Herb Beavers Rd. Follow it all the way (4.4 miles) to a T-junction with Edwards Hill Church Rd (CR 1141), turn right and proceed 4.3 miles south. When this road crosses NC 902, it becomes Tom Hancock Rd.  Follow Tom Hancock Rd. to Vander-Oldham Road (CR 2312).  If you haven’t completed 20 stops, then turn left and continue until you have completed 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.61241167
      , maplon = -79.48801461
      }
    , { county = Chatham
      , number = 6
      , start = "Silk Hope-Liberty Road (CR 1346) 0.4 miles east of junction with Pete Thomas Road (CR 1353) about 5 miles due north of Siler City."
      , name = "Silk Hope-Liberty Road (northwestern Chatham County)"
      , directions = "go west on Silk Hope-Liberty Road a short way and turn right on Sam Lowe Road (CR 1353) (Pete Thomas Road in DeLorme Atlas), proceed north 1.5 miles almost to the county line and turn right on Flint Ridge Road (CR 1351), continue east and southeast all the way back to Silk Hope-Liberty Road (CR 1346), turn left here and continue through Silk Hope, until you have completed 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.81794501
      , maplon = -79.44453999
      }
    , { county = Chatham
      , number = 7
      , start = "Rives Chapel Road 1.7 miles south of US 64 about 5 miles east of Siler City."
      , name = "Rives Chapel Road (CR 2170) (central Chatham County)"
      , directions = "go south on Rives Chapel Road about 1.0 mile to Carolina Hill Road (CR 2168), turn left and continue 2.6 miles to Pleasant Hill Church Road (CR 1506), turn left and in less than 0.5 miles turn right on Jay Shambley Road (CR 2167), continue 3.0 miles to Hadley Mill Road (2165), turn right and proceed 0.7 miles to Elmer Keck Road (CR 2166), turn left and go 1.1 miles to Alex Cockman Road (CR 2163), turn right and go 1.0 miles to Alston Chapel Road (CR 2159), turn left and continue until you have completed 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.71150935
      , maplon = -79.33345279
      }
    , { county = Chatham
      , number = 8
      , start = "Mt. Olive Church Road (County Road 1520) 2.9 miles south of Terrells just south of a chapel marked on the county road map (this location is about 5.4 miles north of US 64 on the west side of Pittsboro – take Old NC 87 which becomes Mt. Olive Church Road about 3.3 miles north of Pittsboro)."
      , name = "Mount Olive Church Road (Terrells) (north-central Chatham County)"
      , directions = "go north on Mt. Olive Church Road all the way to Terrells, turn left on Chicken Bridge Road (CR 1545) and after 0.9 miles keep right on Mann Road (CR 1546) until you reach NC 87, turn left on NC 87 and after 0.7 miles turn right on Big Meadow Road (CR 1549), continue about 4.7 miles (0.4 miles past Van Thomas Road), then turn right on Otis Johnson Road (CR 1552) and continue until you have competed 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.81208045
      , maplon = -79.27649174
      }
    , { county = Chatham
      , number = 9
      , start = "Mount Gilead Church Road (CR 1700) 0.7 miles south of US 15-501 northeast of Bynum."
      , name = "Mount Gilead Church Road (CR 1700) (northeastern Chatham County)"
      , directions = "go south on Mount Gilead Church Road (CR 1700) all the way to Griffins Crossroads, continue straight across US 64 and continue straight into Vista Point Recreation Area (Jordan Lake) as far as possible. At this point, backtrack to the junction with Seaforth Road (CR1941) without making any stops. Turn southwest (to the left as you return from Vista Point) on Seaforth Road (CR 1941) and resume making stops as far as you can go. Once again, backtrack to the junction of Seaforth Road and North Pea Ridge Road without making stops. Then proceed northeast on Seaforth Road (straight ahead this time) and resume making stops. Continue about 2.4 miles to US 64, turn right (east) on US 64 and continue until you have made 20 stops. If stops are not safe on US 64, continue across the lake and turn right on Farrington Road (CR 1008) and proceed south toward Ebenezer Church Recreation Area until you have completed your stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.75209766
      , maplon = -79.05269657
      }
    , { county = Chatham
      , number = 10
      , start = "Gum Springs Church Road (CR 1939) at the junction with Clark Poe Road (CR 1931) – also 1.8 miles northeast of the junction with Moncure-Pittsboro Road (CR 1012) – about 5 miles southeast of Pittsboro."
      , name = "Gum Springs Church Road (southeastern Chatham County)"
      , directions = "go southwest on Gum Springs Church Road (CR 1939) to Moncure-Pittsboro Road (CR 1012), turn right and continue all the way to US 15-501/NC 87, turn right and proceed to Pittsboro center, go around the courthouse and head west on US 64, after about 0.6 miles turn right on NC 87 and soon thereafter branch right on Old NC 87 (CR 1516), continue until you have competed 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.70406138
      , maplon = -79.16932849
      }
    , { county = Chatham
      , number = 11
      , start = "Reno Sharps Store Road (CR 2188) 1.0 mile south of Goldston-Pittsboro Road (CR 1010) just over 2 miles east of Goldston."
      , name = "Reno Sharps Store Road (south-central Chatham County)"
      , directions = "go north on Reno Sharps Store Road (CR 2188) to Goldston-Pittsboro Road (CR 1010), turn right and continue about 3.8 miles until you cross the Rocky River, soon afterward turn right on Holly Ridge Road (CR 2158), after 1.0 mile turn right on Pete Roberson Road (CR 2157), continue 1.6 miles and turn left on Chatham Church Road (CR 1953), after 1.8 miles turn left on Old Sanford Road and then in 0.2 miles turn right on Charlie Brooks Road (CR 1969), cross US 15-501 and continue on Charlie Brooks Road until you have made 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.64743656
      , maplon = -79.24298705
      }
    , { county = Chatham
      , number = 12
      , start = "Sunny Slope Road (CR 1150) 0.8 miles east of Airport Road (CR 1100) about 3.5 miles north of Bennett and Bonlee-Bennett Road."
      , name = "Sunny Slope Road (southwestern Chatham County)"
      , directions = "go south and east on Sunny Slope Road to Devil’s Tramping Ground Road (CR 1100), turn left and proceed 1.0 mile to Bonlee-Bennett Road (CR1005), turn right and go 2.1 miles to Siler City-Glendon Road (CR 1006), turn left and go 1.2 miles (this stretch repeats part of Route 5 but your stops are not likely to fall in the same places), turn right on Mount Vernon Spring Road (CR 1134), continue all the way to Mount Vernon Springs center, cross Old US 421 (the road becomes Foust Road) and immediately turn right on Buck Gunter Road (CR 2119)\n continue eastward straight across US 421 until\n you have completed 20 stops\n (if necessary turn left on Ike Brooks Road CR 2120)."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.64709314
      , maplon = -79.47711654
      }
    , { county = Chatham
      , number = 13
      , start = "Coleridge Road (CR1102) (Blood Run Road in DeLorme Atlas) at the junction with Moons Chapel Road near the county line west of Siler City (6 miles west of the first stoplight in Siler City)"
      , name = "Coleridge Road (northwestern Chatham County)"
      , directions = "go east on Coleridge Road (CR 1102) to Old US 64 (now CR 1107) west of Siler City, turn right and proceed to the center of Siler City  on West Third Street after a bend to the left), turn left on US 421 (North Second Avenue), after two blocks turn right onto Martin Luther King Boulevard, follow a bend to the left, cross US 64, and then head northeast out of Siler City on Snow Camp Road (CR 1004), after about 2.5 miles turn right on Jesse Bridges Road (CR 1332) and continue until you have made 20 stops."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.74211072
      , maplon = -79.49363413
      }
    , { county = Chatham
      , number = 14
      , start = "south end of the causeway over White Oak Creek on Farrington Road (CR 1008) about 0.9 miles north of US 64."
      , name = "Whiteoak Creek (northeastern Chatham County)"
      , directions = "go north on Farrington Road a little over 3.0 miles to Martha’s Chapel Road, turn right and continue to NC 751, turn left and go 1.1 miles to Mt. Pisgah Church Road (CR 1736), turn right and proceed 2.0 miles to a T-junction with New Hope Church Road, turn right and continue until you have completed 20 stops (hopefully before you reach the county line!)."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 35.78304351
      , maplon = -78.9969488
      }
    , { county = Durham
      , number = 1
      , start = "intersection of South Lowell Rd (SR 1461) and Guess Rd (SR 1003)."
      , name = "South Lowell Road NE (northwestern Durham County)"
      , directions = "go north on South Lowell. Just after crossing Little River, turn left onto South Lowell, which becomes SR 1464. Continue to 501, skipping the 4-lane stretch, and turn left onto 501. Turn right onto Moore’s Road and right again onto a gravel road that has no official state road sign. On the left you should immediately see a sign that says Hill Forest and SR 1614. On the right is a DOT diamond-shaped sign that reads “Road subject to flooding”. Go to the end of the road, crossing the Flat River and passing through NC State Univ. forest. Turn left onto Wilkens Road and left again onto Hampton (SR 1603). Turn right onto Red Mountain Road (SR 1471) and continue until you have completed 10 miles."
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 36.18873604
      , maplon = -78.91688497
      }
    , { county = Orange
      , number = 1
      , start = "northernmost point of Wade Loop, 1.5 miles NE of Carr (crossroads on NC 49) and 1 mile north of the junction with NC 49."
      , name = "Wade Loop (northwestern Orange County)"
      , directions = "go south on the eastern arm of Wade Loop to NC 49, turn left on NC 49 for a short distance and then right on McCullough Road, continue east about 1 mile to NC 86 (short jog right and left to cross McDade Store Rd), turn right on NC 86 for a short distance and then right on Efland Cedar Grove Road (the second right turn), continue south on this road through Cedar Grove (crossroads), about 1.5 miles south of Cedar Grove turn left on Highland Farm Road, in about 1.5 miles turn left on Kenion Road"
      , mapid = "1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0"
      , maplat = 36.18883853
      , maplon = -79.20235142
      }
    ]
