{- 
Elm code generated by SpeciesElm-codegen.R
This file should not be modified except by code formatters.
-}
module Data.Species exposing (..) 


-- A record containing information and data about an individual species
type alias SpeciesRec =
    { species : Species
    , id : String
    , commonName : String
    , sciName : String
    , rate : Float
    , pvalue : Float
    } 


-- Enumeration of all species observed in MBBS.
type Species 
   = AcadianFlycatcher
   | AmericanCrow
   | AmericanGoldfinch
   | AmericanRedstart
   | AmericanRobin
   | BaldEagle
   | BaltimoreOriole
   | BarnSwallow
   | BarredOwl
   | BeltedKingfisher
   | BlackVulture
   | BlackandwhiteWarbler
   | BlueGrosbeak
   | BlueJay
   | BluegrayGnatcatcher
   | BlueheadedVireo
   | BroadwingedHawk
   | BrownThrasher
   | BrownheadedCowbird
   | BrownheadedNuthatch
   | CanadaGoose
   | CarolinaChickadee
   | CarolinaWren
   | CedarWaxwing
   | ChimneySwift
   | ChippingSparrow
   | Chuckwillswidow
   | CliffSwallow
   | CommonGrackle
   | CommonYellowthroat
   | CoopersHawk
   | Dickcissel
   | DoublecrestedCormorant
   | DownyWoodpecker
   | EasternBluebird
   | EasternKingbird
   | EasternMeadowlark
   | EasternPhoebe
   | EasternScreechOwl
   | EasternTowhee
   | EasternWhippoorwill
   | EasternWoodPewee
   | EuropeanStarling
   | FieldSparrow
   | FishCrow
   | GrasshopperSparrow
   | GrayCatbird
   | GreatBlueHeron
   | GreatCrestedFlycatcher
   | GreatHornedOwl
   | GreenHeron
   | HairyWoodpecker
   | HoodedWarbler
   | HouseFinch
   | HouseSparrow
   | IndigoBunting
   | KentuckyWarbler
   | Killdeer
   | LoggerheadShrike
   | LouisianaWaterthrush
   | Mallard
   | MourningDove
   | NorthernBobwhite
   | NorthernCardinal
   | NorthernFlicker
   | NorthernHouseWren
   | NorthernMockingbird
   | NorthernParula
   | NorthernRoughwingedSwallow
   | OrchardOriole
   | Osprey
   | Ovenbird
   | PileatedWoodpecker
   | PineWarbler
   | PrairieWarbler
   | ProthonotaryWarbler
   | PurpleMartin
   | RedbelliedWoodpecker
   | RedeyedVireo
   | RedheadedWoodpecker
   | RedshoulderedHawk
   | RedtailedHawk
   | RedwingedBlackbird
   | RockPigeon
   | RubythroatedHummingbird
   | ScarletTanager
   | SharpshinnedHawk
   | SongSparrow
   | SummerTanager
   | TreeSwallow
   | TuftedTitmouse
   | TurkeyVulture
   | WarblingVireo
   | WhitebreastedNuthatch
   | WhiteeyedVireo
   | WildTurkey
   | WoodDuck
   | WoodThrush
   | YellowWarbler
   | YellowbilledCuckoo
   | YellowbreastedChat
   | YellowthroatedVireo
   | YellowthroatedWarbler 


-- All Species in a single list
allSpecies : List Species
allSpecies 
   = [ AcadianFlycatcher
    , AmericanCrow
    , AmericanGoldfinch
    , AmericanRedstart
    , AmericanRobin
    , BaldEagle
    , BaltimoreOriole
    , BarnSwallow
    , BarredOwl
    , BeltedKingfisher
    , BlackVulture
    , BlackandwhiteWarbler
    , BlueGrosbeak
    , BlueJay
    , BluegrayGnatcatcher
    , BlueheadedVireo
    , BroadwingedHawk
    , BrownThrasher
    , BrownheadedCowbird
    , BrownheadedNuthatch
    , CanadaGoose
    , CarolinaChickadee
    , CarolinaWren
    , CedarWaxwing
    , ChimneySwift
    , ChippingSparrow
    , Chuckwillswidow
    , CliffSwallow
    , CommonGrackle
    , CommonYellowthroat
    , CoopersHawk
    , Dickcissel
    , DoublecrestedCormorant
    , DownyWoodpecker
    , EasternBluebird
    , EasternKingbird
    , EasternMeadowlark
    , EasternPhoebe
    , EasternScreechOwl
    , EasternTowhee
    , EasternWhippoorwill
    , EasternWoodPewee
    , EuropeanStarling
    , FieldSparrow
    , FishCrow
    , GrasshopperSparrow
    , GrayCatbird
    , GreatBlueHeron
    , GreatCrestedFlycatcher
    , GreatHornedOwl
    , GreenHeron
    , HairyWoodpecker
    , HoodedWarbler
    , HouseFinch
    , HouseSparrow
    , IndigoBunting
    , KentuckyWarbler
    , Killdeer
    , LoggerheadShrike
    , LouisianaWaterthrush
    , Mallard
    , MourningDove
    , NorthernBobwhite
    , NorthernCardinal
    , NorthernFlicker
    , NorthernHouseWren
    , NorthernMockingbird
    , NorthernParula
    , NorthernRoughwingedSwallow
    , OrchardOriole
    , Osprey
    , Ovenbird
    , PileatedWoodpecker
    , PineWarbler
    , PrairieWarbler
    , ProthonotaryWarbler
    , PurpleMartin
    , RedbelliedWoodpecker
    , RedeyedVireo
    , RedheadedWoodpecker
    , RedshoulderedHawk
    , RedtailedHawk
    , RedwingedBlackbird
    , RockPigeon
    , RubythroatedHummingbird
    , ScarletTanager
    , SharpshinnedHawk
    , SongSparrow
    , SummerTanager
    , TreeSwallow
    , TuftedTitmouse
    , TurkeyVulture
    , WarblingVireo
    , WhitebreastedNuthatch
    , WhiteeyedVireo
    , WildTurkey
    , WoodDuck
    , WoodThrush
    , YellowWarbler
    , YellowbilledCuckoo
    , YellowbreastedChat
    , YellowthroatedVireo
    , YellowthroatedWarbler ] 


-- All Species records in a single list
allSpeciesRec : List SpeciesRec
allSpeciesRec 
   = [ { species = AcadianFlycatcher
  , id = "AcadianFlycatcher" 
  , commonName = "Acadian Flycatcher"
  , sciName = "Empidonax virescens"
  , rate = 0.061971528081
  , pvalue =  0.000000000007
  }
  , { species = AmericanCrow
  , id = "AmericanCrow" 
  , commonName = "American Crow"
  , sciName = "Corvus brachyrhynchos"
  , rate = -0.008186408221
  , pvalue =  0.000955550976
  }
  , { species = AmericanGoldfinch
  , id = "AmericanGoldfinch" 
  , commonName = "American Goldfinch"
  , sciName = "Spinus tristis"
  , rate = -0.030940734748
  , pvalue =  0.000000121272
  }
  , { species = AmericanRedstart
  , id = "AmericanRedstart" 
  , commonName = "American Redstart"
  , sciName = "Setophaga ruticilla"
  , rate = -0.025818058907
  , pvalue =  0.501553650890
  }
  , { species = AmericanRobin
  , id = "AmericanRobin" 
  , commonName = "American Robin"
  , sciName = "Turdus migratorius"
  , rate = -0.021352125807
  , pvalue =  0.005517289250
  }
  , { species = BaldEagle
  , id = "BaldEagle" 
  , commonName = "Bald Eagle"
  , sciName = "Haliaeetus leucocephalus"
  , rate = 0.063828500792
  , pvalue =  0.386303669963
  }
  , { species = BaltimoreOriole
  , id = "BaltimoreOriole" 
  , commonName = "Baltimore Oriole"
  , sciName = "Icterus galbula"
  , rate = 0.000000000000
  , pvalue =  1.000000000000
  }
  , { species = BarnSwallow
  , id = "BarnSwallow" 
  , commonName = "Barn Swallow"
  , sciName = "Hirundo rustica"
  , rate = -0.024692587083
  , pvalue =  0.033724642252
  }
  , { species = BarredOwl
  , id = "BarredOwl" 
  , commonName = "Barred Owl"
  , sciName = "Strix varia"
  , rate = 0.029509045171
  , pvalue =  0.017372300108
  }
  , { species = BeltedKingfisher
  , id = "BeltedKingfisher" 
  , commonName = "Belted Kingfisher"
  , sciName = "Megaceryle alcyon"
  , rate = -0.071331292848
  , pvalue =  0.014423777500
  }
  , { species = BlackVulture
  , id = "BlackVulture" 
  , commonName = "Black Vulture"
  , sciName = "Coragyps atratus"
  , rate = 0.060948919205
  , pvalue =  0.010244494351
  }
  , { species = BlackandwhiteWarbler
  , id = "BlackandwhiteWarbler" 
  , commonName = "Black-and-white Warbler"
  , sciName = "Mniotilta varia"
  , rate = 0.047585550617
  , pvalue =  0.021168484622
  }
  , { species = BlueGrosbeak
  , id = "BlueGrosbeak" 
  , commonName = "Blue Grosbeak"
  , sciName = "Passerina caerulea"
  , rate = 0.006941054165
  , pvalue =  0.392439892164
  }
  , { species = BlueJay
  , id = "BlueJay" 
  , commonName = "Blue Jay"
  , sciName = "Cyanocitta cristata"
  , rate = -0.017635538186
  , pvalue =  0.000606992713
  }
  , { species = BluegrayGnatcatcher
  , id = "BluegrayGnatcatcher" 
  , commonName = "Blue-gray Gnatcatcher"
  , sciName = "Polioptila caerulea"
  , rate = 0.006893102615
  , pvalue =  0.242508461676
  }
  , { species = BlueheadedVireo
  , id = "BlueheadedVireo" 
  , commonName = "Blue-headed Vireo"
  , sciName = "Vireo solitarius"
  , rate = -0.055194992960
  , pvalue =  0.000127461686
  }
  , { species = BroadwingedHawk
  , id = "BroadwingedHawk" 
  , commonName = "Broad-winged Hawk"
  , sciName = "Buteo platypterus"
  , rate = -0.101935667402
  , pvalue =  0.000000000097
  }
  , { species = BrownThrasher
  , id = "BrownThrasher" 
  , commonName = "Brown Thrasher"
  , sciName = "Toxostoma rufum"
  , rate = -0.000663983119
  , pvalue =  0.915960701233
  }
  , { species = BrownheadedCowbird
  , id = "BrownheadedCowbird" 
  , commonName = "Brown-headed Cowbird"
  , sciName = "Molothrus ater"
  , rate = 0.008548195166
  , pvalue =  0.231644574984
  }
  , { species = BrownheadedNuthatch
  , id = "BrownheadedNuthatch" 
  , commonName = "Brown-headed Nuthatch"
  , sciName = "Sitta pusilla"
  , rate = 0.015677657361
  , pvalue =  0.251199965772
  }
  , { species = CanadaGoose
  , id = "CanadaGoose" 
  , commonName = "Canada Goose"
  , sciName = "Branta canadensis"
  , rate = -0.028960428571
  , pvalue =  0.189904158160
  }
  , { species = CarolinaChickadee
  , id = "CarolinaChickadee" 
  , commonName = "Carolina Chickadee"
  , sciName = "Poecile carolinensis"
  , rate = -0.001050638447
  , pvalue =  0.821170742966
  }
  , { species = CarolinaWren
  , id = "CarolinaWren" 
  , commonName = "Carolina Wren"
  , sciName = "Thryothorus ludovicianus"
  , rate = 0.007146551778
  , pvalue =  0.035671339777
  }
  , { species = CedarWaxwing
  , id = "CedarWaxwing" 
  , commonName = "Cedar Waxwing"
  , sciName = "Bombycilla cedrorum"
  , rate = -0.011649893348
  , pvalue =  0.510369218050
  }
  , { species = ChimneySwift
  , id = "ChimneySwift" 
  , commonName = "Chimney Swift"
  , sciName = "Chaetura pelagica"
  , rate = -0.035028366017
  , pvalue =  0.000001533368
  }
  , { species = ChippingSparrow
  , id = "ChippingSparrow" 
  , commonName = "Chipping Sparrow"
  , sciName = "Spizella passerina"
  , rate = 0.012477913958
  , pvalue =  0.010413215881
  }
  , { species = Chuckwillswidow
  , id = "Chuckwillswidow" 
  , commonName = "Chuck-will's-widow"
  , sciName = "Antrostomus carolinensis"
  , rate = 0.005541479468
  , pvalue =  0.798727621945
  }
  , { species = CliffSwallow
  , id = "CliffSwallow" 
  , commonName = "Cliff Swallow"
  , sciName = "Petrochelidon pyrrhonota"
  , rate = 0.154123417822
  , pvalue =  0.000000000000
  }
  , { species = CommonGrackle
  , id = "CommonGrackle" 
  , commonName = "Common Grackle"
  , sciName = "Quiscalus quiscula"
  , rate = -0.059193880195
  , pvalue =  0.000000000005
  }
  , { species = CommonYellowthroat
  , id = "CommonYellowthroat" 
  , commonName = "Common Yellowthroat"
  , sciName = "Geothlypis trichas"
  , rate = -0.030713875078
  , pvalue =  0.000251869679
  }
  , { species = CoopersHawk
  , id = "CoopersHawk" 
  , commonName = "Cooper's Hawk"
  , sciName = "Astur cooperii"
  , rate = -0.005449622875
  , pvalue =  0.761534931181
  }
  , { species = Dickcissel
  , id = "Dickcissel" 
  , commonName = "Dickcissel"
  , sciName = "Spiza americana"
  , rate = 0.000000000000
  , pvalue =  1.000000000000
  }
  , { species = DoublecrestedCormorant
  , id = "DoublecrestedCormorant" 
  , commonName = "Double-crested Cormorant"
  , sciName = "Nannopterum auritum"
  , rate = 0.028430116750
  , pvalue =  0.210859494041
  }
  , { species = DownyWoodpecker
  , id = "DownyWoodpecker" 
  , commonName = "Downy Woodpecker"
  , sciName = "Dryobates pubescens"
  , rate = 0.009001651161
  , pvalue =  0.271507039159
  }
  , { species = EasternBluebird
  , id = "EasternBluebird" 
  , commonName = "Eastern Bluebird"
  , sciName = "Sialia sialis"
  , rate = 0.001112604383
  , pvalue =  0.770536331434
  }
  , { species = EasternKingbird
  , id = "EasternKingbird" 
  , commonName = "Eastern Kingbird"
  , sciName = "Tyrannus tyrannus"
  , rate = -0.018559071416
  , pvalue =  0.114109249942
  }
  , { species = EasternMeadowlark
  , id = "EasternMeadowlark" 
  , commonName = "Eastern Meadowlark"
  , sciName = "Sturnella magna"
  , rate = -0.027072484997
  , pvalue =  0.004266751301
  }
  , { species = EasternPhoebe
  , id = "EasternPhoebe" 
  , commonName = "Eastern Phoebe"
  , sciName = "Sayornis phoebe"
  , rate = 0.011383516188
  , pvalue =  0.034193657085
  }
  , { species = EasternScreechOwl
  , id = "EasternScreechOwl" 
  , commonName = "Eastern Screech-Owl"
  , sciName = "Megascops asio"
  , rate = 0.049745246496
  , pvalue =  0.382237298626
  }
  , { species = EasternTowhee
  , id = "EasternTowhee" 
  , commonName = "Eastern Towhee"
  , sciName = "Pipilo erythrophthalmus"
  , rate = -0.030577828253
  , pvalue =  0.000000000000
  }
  , { species = EasternWhippoorwill
  , id = "EasternWhippoorwill" 
  , commonName = "Eastern Whip-poor-will"
  , sciName = "Antrostomus vociferus"
  , rate = -0.052453751355
  , pvalue =  0.003623193385
  }
  , { species = EasternWoodPewee
  , id = "EasternWoodPewee" 
  , commonName = "Eastern Wood-Pewee"
  , sciName = "Contopus virens"
  , rate = -0.007465773567
  , pvalue =  0.172869435210
  }
  , { species = EuropeanStarling
  , id = "EuropeanStarling" 
  , commonName = "European Starling"
  , sciName = "Sturnus vulgaris"
  , rate = -0.031428009159
  , pvalue =  0.006285830827
  }
  , { species = FieldSparrow
  , id = "FieldSparrow" 
  , commonName = "Field Sparrow"
  , sciName = "Spizella pusilla"
  , rate = -0.044592809630
  , pvalue =  0.001332093097
  }
  , { species = FishCrow
  , id = "FishCrow" 
  , commonName = "Fish Crow"
  , sciName = "Corvus ossifragus"
  , rate = 0.061982492692
  , pvalue =  0.000000000000
  }
  , { species = GrasshopperSparrow
  , id = "GrasshopperSparrow" 
  , commonName = "Grasshopper Sparrow"
  , sciName = "Ammodramus savannarum"
  , rate = -0.004161097246
  , pvalue =  0.850066213452
  }
  , { species = GrayCatbird
  , id = "GrayCatbird" 
  , commonName = "Gray Catbird"
  , sciName = "Dumetella carolinensis"
  , rate = -0.011307395757
  , pvalue =  0.143649932007
  }
  , { species = GreatBlueHeron
  , id = "GreatBlueHeron" 
  , commonName = "Great Blue Heron"
  , sciName = "Ardea herodias"
  , rate = 0.008842215286
  , pvalue =  0.333305539921
  }
  , { species = GreatCrestedFlycatcher
  , id = "GreatCrestedFlycatcher" 
  , commonName = "Great Crested Flycatcher"
  , sciName = "Myiarchus crinitus"
  , rate = 0.036431278956
  , pvalue =  0.000000697962
  }
  , { species = GreatHornedOwl
  , id = "GreatHornedOwl" 
  , commonName = "Great Horned Owl"
  , sciName = "Bubo virginianus"
  , rate = -0.014223342204
  , pvalue =  0.663038709419
  }
  , { species = GreenHeron
  , id = "GreenHeron" 
  , commonName = "Green Heron"
  , sciName = "Butorides virescens"
  , rate = -0.047726421341
  , pvalue =  0.004418514612
  }
  , { species = HairyWoodpecker
  , id = "HairyWoodpecker" 
  , commonName = "Hairy Woodpecker"
  , sciName = "Dryobates villosus"
  , rate = -0.012385945970
  , pvalue =  0.503793923140
  }
  , { species = HoodedWarbler
  , id = "HoodedWarbler" 
  , commonName = "Hooded Warbler"
  , sciName = "Setophaga citrina"
  , rate = 0.023660305674
  , pvalue =  0.000090739499
  }
  , { species = HouseFinch
  , id = "HouseFinch" 
  , commonName = "House Finch"
  , sciName = "Haemorhous mexicanus"
  , rate = 0.001290688600
  , pvalue =  0.862016072811
  }
  , { species = HouseSparrow
  , id = "HouseSparrow" 
  , commonName = "House Sparrow"
  , sciName = "Passer domesticus"
  , rate = -0.076497613745
  , pvalue =  0.000002734883
  }
  , { species = IndigoBunting
  , id = "IndigoBunting" 
  , commonName = "Indigo Bunting"
  , sciName = "Passerina cyanea"
  , rate = -0.027569197949
  , pvalue =  0.000000003286
  }
  , { species = KentuckyWarbler
  , id = "KentuckyWarbler" 
  , commonName = "Kentucky Warbler"
  , sciName = "Geothlypis formosa"
  , rate = 0.033136001245
  , pvalue =  0.352255847422
  }
  , { species = Killdeer
  , id = "Killdeer" 
  , commonName = "Killdeer"
  , sciName = "Charadrius vociferus"
  , rate = -0.019736004701
  , pvalue =  0.186059707942
  }
  , { species = LoggerheadShrike
  , id = "LoggerheadShrike" 
  , commonName = "Loggerhead Shrike"
  , sciName = "Lanius ludovicianus"
  , rate = -0.001383641509
  , pvalue =  0.984618128553
  }
  , { species = LouisianaWaterthrush
  , id = "LouisianaWaterthrush" 
  , commonName = "Louisiana Waterthrush"
  , sciName = "Parkesia motacilla"
  , rate = 0.021101279418
  , pvalue =  0.290913887424
  }
  , { species = Mallard
  , id = "Mallard" 
  , commonName = "Mallard"
  , sciName = "Anas platyrhynchos"
  , rate = -0.040771514109
  , pvalue =  0.030238300135
  }
  , { species = MourningDove
  , id = "MourningDove" 
  , commonName = "Mourning Dove"
  , sciName = "Zenaida macroura"
  , rate = -0.011855579672
  , pvalue =  0.004125080127
  }
  , { species = NorthernBobwhite
  , id = "NorthernBobwhite" 
  , commonName = "Northern Bobwhite"
  , sciName = "Colinus virginianus"
  , rate = -0.116265612030
  , pvalue =  0.000000000483
  }
  , { species = NorthernCardinal
  , id = "NorthernCardinal" 
  , commonName = "Northern Cardinal"
  , sciName = "Cardinalis cardinalis"
  , rate = -0.004556000352
  , pvalue =  0.070605206599
  }
  , { species = NorthernFlicker
  , id = "NorthernFlicker" 
  , commonName = "Northern Flicker"
  , sciName = "Colaptes auratus"
  , rate = -0.042540155638
  , pvalue =  0.002420437624
  }
  , { species = NorthernHouseWren
  , id = "NorthernHouseWren" 
  , commonName = "Northern House Wren"
  , sciName = "Troglodytes aedon"
  , rate = -0.042036997601
  , pvalue =  0.018811114611
  }
  , { species = NorthernMockingbird
  , id = "NorthernMockingbird" 
  , commonName = "Northern Mockingbird"
  , sciName = "Mimus polyglottos"
  , rate = -0.010011485626
  , pvalue =  0.024013137355
  }
  , { species = NorthernParula
  , id = "NorthernParula" 
  , commonName = "Northern Parula"
  , sciName = "Setophaga americana"
  , rate = 0.035243995669
  , pvalue =  0.008215596196
  }
  , { species = NorthernRoughwingedSwallow
  , id = "NorthernRoughwingedSwallow" 
  , commonName = "Northern Rough-winged Swallow"
  , sciName = "Stelgidopteryx serripennis"
  , rate = 0.010327188432
  , pvalue =  0.703722680937
  }
  , { species = OrchardOriole
  , id = "OrchardOriole" 
  , commonName = "Orchard Oriole"
  , sciName = "Icterus spurius"
  , rate = -0.022130318047
  , pvalue =  0.048215558614
  }
  , { species = Osprey
  , id = "Osprey" 
  , commonName = "Osprey"
  , sciName = "Pandion haliaetus"
  , rate = 0.065791826269
  , pvalue =  0.001442225257
  }
  , { species = Ovenbird
  , id = "Ovenbird" 
  , commonName = "Ovenbird"
  , sciName = "Seiurus aurocapilla"
  , rate = -0.002524003268
  , pvalue =  0.545054010040
  }
  , { species = PileatedWoodpecker
  , id = "PileatedWoodpecker" 
  , commonName = "Pileated Woodpecker"
  , sciName = "Dryocopus pileatus"
  , rate = 0.038801571873
  , pvalue =  0.001339295457
  }
  , { species = PineWarbler
  , id = "PineWarbler" 
  , commonName = "Pine Warbler"
  , sciName = "Setophaga pinus"
  , rate = -0.005358641633
  , pvalue =  0.183558202078
  }
  , { species = PrairieWarbler
  , id = "PrairieWarbler" 
  , commonName = "Prairie Warbler"
  , sciName = "Setophaga discolor"
  , rate = -0.041676052268
  , pvalue =  0.000000008813
  }
  , { species = ProthonotaryWarbler
  , id = "ProthonotaryWarbler" 
  , commonName = "Prothonotary Warbler"
  , sciName = "Protonotaria citrea"
  , rate = 0.030334973755
  , pvalue =  0.250495266650
  }
  , { species = PurpleMartin
  , id = "PurpleMartin" 
  , commonName = "Purple Martin"
  , sciName = "Progne subis"
  , rate = 0.013163614579
  , pvalue =  0.130601803293
  }
  , { species = RedbelliedWoodpecker
  , id = "RedbelliedWoodpecker" 
  , commonName = "Red-bellied Woodpecker"
  , sciName = "Melanerpes carolinus"
  , rate = 0.001523579134
  , pvalue =  0.681791252884
  }
  , { species = RedeyedVireo
  , id = "RedeyedVireo" 
  , commonName = "Red-eyed Vireo"
  , sciName = "Vireo olivaceus"
  , rate = -0.010437713182
  , pvalue =  0.048594354286
  }
  , { species = RedheadedWoodpecker
  , id = "RedheadedWoodpecker" 
  , commonName = "Red-headed Woodpecker"
  , sciName = "Melanerpes erythrocephalus"
  , rate = 0.017903781880
  , pvalue =  0.288811767148
  }
  , { species = RedshoulderedHawk
  , id = "RedshoulderedHawk" 
  , commonName = "Red-shouldered Hawk"
  , sciName = "Buteo lineatus"
  , rate = 0.054438600148
  , pvalue =  0.000000001923
  }
  , { species = RedtailedHawk
  , id = "RedtailedHawk" 
  , commonName = "Red-tailed Hawk"
  , sciName = "Buteo jamaicensis"
  , rate = 0.006839905567
  , pvalue =  0.613716583610
  }
  , { species = RedwingedBlackbird
  , id = "RedwingedBlackbird" 
  , commonName = "Red-winged Blackbird"
  , sciName = "Agelaius phoeniceus"
  , rate = -0.027354283232
  , pvalue =  0.016830428331
  }
  , { species = RockPigeon
  , id = "RockPigeon" 
  , commonName = "Rock Pigeon"
  , sciName = "Columba livia"
  , rate = -0.041860804180
  , pvalue =  0.036410923725
  }
  , { species = RubythroatedHummingbird
  , id = "RubythroatedHummingbird" 
  , commonName = "Ruby-throated Hummingbird"
  , sciName = "Archilochus colubris"
  , rate = -0.036475169024
  , pvalue =  0.000382764901
  }
  , { species = ScarletTanager
  , id = "ScarletTanager" 
  , commonName = "Scarlet Tanager"
  , sciName = "Piranga olivacea"
  , rate = -0.041713481269
  , pvalue =  0.000000016929
  }
  , { species = SharpshinnedHawk
  , id = "SharpshinnedHawk" 
  , commonName = "Sharp-shinned Hawk"
  , sciName = "Accipiter striatus"
  , rate = -0.058173119660
  , pvalue =  0.112953942702
  }
  , { species = SongSparrow
  , id = "SongSparrow" 
  , commonName = "Song Sparrow"
  , sciName = "Melospiza melodia"
  , rate = 0.032362498220
  , pvalue =  0.024118791513
  }
  , { species = SummerTanager
  , id = "SummerTanager" 
  , commonName = "Summer Tanager"
  , sciName = "Piranga rubra"
  , rate = 0.023782122550
  , pvalue =  0.000143449648
  }
  , { species = TreeSwallow
  , id = "TreeSwallow" 
  , commonName = "Tree Swallow"
  , sciName = "Tachycineta bicolor"
  , rate = 0.125529581627
  , pvalue =  0.000129202291
  }
  , { species = TuftedTitmouse
  , id = "TuftedTitmouse" 
  , commonName = "Tufted Titmouse"
  , sciName = "Baeolophus bicolor"
  , rate = 0.003772199827
  , pvalue =  0.309334791371
  }
  , { species = TurkeyVulture
  , id = "TurkeyVulture" 
  , commonName = "Turkey Vulture"
  , sciName = "Cathartes aura"
  , rate = 0.008440019238
  , pvalue =  0.612300347932
  }
  , { species = WarblingVireo
  , id = "WarblingVireo" 
  , commonName = "Warbling Vireo"
  , sciName = "Vireo gilvus"
  , rate = -0.162402841319
  , pvalue =  0.024582031656
  }
  , { species = WhitebreastedNuthatch
  , id = "WhitebreastedNuthatch" 
  , commonName = "White-breasted Nuthatch"
  , sciName = "Sitta carolinensis"
  , rate = 0.018367665299
  , pvalue =  0.051518905695
  }
  , { species = WhiteeyedVireo
  , id = "WhiteeyedVireo" 
  , commonName = "White-eyed Vireo"
  , sciName = "Vireo griseus"
  , rate = 0.066969220978
  , pvalue =  0.000000001073
  }
  , { species = WildTurkey
  , id = "WildTurkey" 
  , commonName = "Wild Turkey"
  , sciName = "Meleagris gallopavo"
  , rate = 0.064226656142
  , pvalue =  0.000381034696
  }
  , { species = WoodDuck
  , id = "WoodDuck" 
  , commonName = "Wood Duck"
  , sciName = "Aix sponsa"
  , rate = 0.007724677171
  , pvalue =  0.792908324152
  }
  , { species = WoodThrush
  , id = "WoodThrush" 
  , commonName = "Wood Thrush"
  , sciName = "Hylocichla mustelina"
  , rate = -0.060855784503
  , pvalue =  0.000000000000
  }
  , { species = YellowWarbler
  , id = "YellowWarbler" 
  , commonName = "Yellow Warbler"
  , sciName = "Setophaga petechia"
  , rate = 0.033136001245
  , pvalue =  0.344937656727
  }
  , { species = YellowbilledCuckoo
  , id = "YellowbilledCuckoo" 
  , commonName = "Yellow-billed Cuckoo"
  , sciName = "Coccyzus americanus"
  , rate = 0.015204036651
  , pvalue =  0.013343835679
  }
  , { species = YellowbreastedChat
  , id = "YellowbreastedChat" 
  , commonName = "Yellow-breasted Chat"
  , sciName = "Icteria virens"
  , rate = -0.037980271789
  , pvalue =  0.000000289272
  }
  , { species = YellowthroatedVireo
  , id = "YellowthroatedVireo" 
  , commonName = "Yellow-throated Vireo"
  , sciName = "Vireo flavifrons"
  , rate = -0.011462304273
  , pvalue =  0.407714494098
  }
  , { species = YellowthroatedWarbler
  , id = "YellowthroatedWarbler" 
  , commonName = "Yellow-throated Warbler"
  , sciName = "Setophaga dominica"
  , rate = 0.070502687901
  , pvalue =  0.000000069069
  } ] 


-- Convert species to its common name as a String.
speciesToString : Species -> String
speciesToString species =
    case species of 
      AcadianFlycatcher -> "Acadian Flycatcher"
      AmericanCrow -> "American Crow"
      AmericanGoldfinch -> "American Goldfinch"
      AmericanRedstart -> "American Redstart"
      AmericanRobin -> "American Robin"
      BaldEagle -> "Bald Eagle"
      BaltimoreOriole -> "Baltimore Oriole"
      BarnSwallow -> "Barn Swallow"
      BarredOwl -> "Barred Owl"
      BeltedKingfisher -> "Belted Kingfisher"
      BlackVulture -> "Black Vulture"
      BlackandwhiteWarbler -> "Black-and-white Warbler"
      BlueGrosbeak -> "Blue Grosbeak"
      BlueJay -> "Blue Jay"
      BluegrayGnatcatcher -> "Blue-gray Gnatcatcher"
      BlueheadedVireo -> "Blue-headed Vireo"
      BroadwingedHawk -> "Broad-winged Hawk"
      BrownThrasher -> "Brown Thrasher"
      BrownheadedCowbird -> "Brown-headed Cowbird"
      BrownheadedNuthatch -> "Brown-headed Nuthatch"
      CanadaGoose -> "Canada Goose"
      CarolinaChickadee -> "Carolina Chickadee"
      CarolinaWren -> "Carolina Wren"
      CedarWaxwing -> "Cedar Waxwing"
      ChimneySwift -> "Chimney Swift"
      ChippingSparrow -> "Chipping Sparrow"
      Chuckwillswidow -> "Chuck-will's-widow"
      CliffSwallow -> "Cliff Swallow"
      CommonGrackle -> "Common Grackle"
      CommonYellowthroat -> "Common Yellowthroat"
      CoopersHawk -> "Cooper's Hawk"
      Dickcissel -> "Dickcissel"
      DoublecrestedCormorant -> "Double-crested Cormorant"
      DownyWoodpecker -> "Downy Woodpecker"
      EasternBluebird -> "Eastern Bluebird"
      EasternKingbird -> "Eastern Kingbird"
      EasternMeadowlark -> "Eastern Meadowlark"
      EasternPhoebe -> "Eastern Phoebe"
      EasternScreechOwl -> "Eastern Screech-Owl"
      EasternTowhee -> "Eastern Towhee"
      EasternWhippoorwill -> "Eastern Whip-poor-will"
      EasternWoodPewee -> "Eastern Wood-Pewee"
      EuropeanStarling -> "European Starling"
      FieldSparrow -> "Field Sparrow"
      FishCrow -> "Fish Crow"
      GrasshopperSparrow -> "Grasshopper Sparrow"
      GrayCatbird -> "Gray Catbird"
      GreatBlueHeron -> "Great Blue Heron"
      GreatCrestedFlycatcher -> "Great Crested Flycatcher"
      GreatHornedOwl -> "Great Horned Owl"
      GreenHeron -> "Green Heron"
      HairyWoodpecker -> "Hairy Woodpecker"
      HoodedWarbler -> "Hooded Warbler"
      HouseFinch -> "House Finch"
      HouseSparrow -> "House Sparrow"
      IndigoBunting -> "Indigo Bunting"
      KentuckyWarbler -> "Kentucky Warbler"
      Killdeer -> "Killdeer"
      LoggerheadShrike -> "Loggerhead Shrike"
      LouisianaWaterthrush -> "Louisiana Waterthrush"
      Mallard -> "Mallard"
      MourningDove -> "Mourning Dove"
      NorthernBobwhite -> "Northern Bobwhite"
      NorthernCardinal -> "Northern Cardinal"
      NorthernFlicker -> "Northern Flicker"
      NorthernHouseWren -> "Northern House Wren"
      NorthernMockingbird -> "Northern Mockingbird"
      NorthernParula -> "Northern Parula"
      NorthernRoughwingedSwallow -> "Northern Rough-winged Swallow"
      OrchardOriole -> "Orchard Oriole"
      Osprey -> "Osprey"
      Ovenbird -> "Ovenbird"
      PileatedWoodpecker -> "Pileated Woodpecker"
      PineWarbler -> "Pine Warbler"
      PrairieWarbler -> "Prairie Warbler"
      ProthonotaryWarbler -> "Prothonotary Warbler"
      PurpleMartin -> "Purple Martin"
      RedbelliedWoodpecker -> "Red-bellied Woodpecker"
      RedeyedVireo -> "Red-eyed Vireo"
      RedheadedWoodpecker -> "Red-headed Woodpecker"
      RedshoulderedHawk -> "Red-shouldered Hawk"
      RedtailedHawk -> "Red-tailed Hawk"
      RedwingedBlackbird -> "Red-winged Blackbird"
      RockPigeon -> "Rock Pigeon"
      RubythroatedHummingbird -> "Ruby-throated Hummingbird"
      ScarletTanager -> "Scarlet Tanager"
      SharpshinnedHawk -> "Sharp-shinned Hawk"
      SongSparrow -> "Song Sparrow"
      SummerTanager -> "Summer Tanager"
      TreeSwallow -> "Tree Swallow"
      TuftedTitmouse -> "Tufted Titmouse"
      TurkeyVulture -> "Turkey Vulture"
      WarblingVireo -> "Warbling Vireo"
      WhitebreastedNuthatch -> "White-breasted Nuthatch"
      WhiteeyedVireo -> "White-eyed Vireo"
      WildTurkey -> "Wild Turkey"
      WoodDuck -> "Wood Duck"
      WoodThrush -> "Wood Thrush"
      YellowWarbler -> "Yellow Warbler"
      YellowbilledCuckoo -> "Yellow-billed Cuckoo"
      YellowbreastedChat -> "Yellow-breasted Chat"
      YellowthroatedVireo -> "Yellow-throated Vireo"
      YellowthroatedWarbler -> "Yellow-throated Warbler" 


-- Identify a Species by a string, maybe
stringToSpecies : String -> Maybe Species
stringToSpecies s =
    List.map (\x -> ( x, speciesToString x )) allSpecies
   |> List.filterMap
      (\( x, y ) -> if y == s then Just x else Nothing )
    |> List.head 


-- Get the SpeciesRec for a Species
lookupSpecies : Species -> Maybe SpeciesRec
lookupSpecies x = 
  List.filter (\r -> x == r.species) allSpeciesRec 
    |> List.head
