{-
   Elm code generated by SpeciesElm-codegen.R
   This file should not be modified except by code formatters.
-}


module Data.Species exposing (..)

-- A record containing information and data about an individual species


type alias SpeciesRec =
    { species : Species
    , id : String
    , commonName : String
    , sciName : String
    , rate : Float
    , pvalue : Float
    }



-- Enumeration of all species observed in MBBS.


type Species
    = AcadianFlycatcher
    | AmericanCrow
    | AmericanGoldfinch
    | AmericanRedstart
    | AmericanRobin
    | BaldEagle
    | BaltimoreOriole
    | BarnSwallow
    | BarredOwl
    | BeltedKingfisher
    | BlackVulture
    | BlackandwhiteWarbler
    | BlueGrosbeak
    | BlueJay
    | BluegrayGnatcatcher
    | BlueheadedVireo
    | BroadwingedHawk
    | BrownThrasher
    | BrownheadedCowbird
    | BrownheadedNuthatch
    | CanadaGoose
    | CarolinaChickadee
    | CarolinaWren
    | CedarWaxwing
    | ChimneySwift
    | ChippingSparrow
    | Chuckwillswidow
    | CliffSwallow
    | CommonGrackle
    | CommonNighthawk
    | CommonYellowthroat
    | CoopersHawk
    | Dickcissel
    | DoublecrestedCormorant
    | DownyWoodpecker
    | EasternBluebird
    | EasternKingbird
    | EasternMeadowlark
    | EasternPhoebe
    | EasternScreechOwl
    | EasternTowhee
    | EasternWhippoorwill
    | EasternWoodPewee
    | EuropeanStarling
    | FieldSparrow
    | FishCrow
    | GrasshopperSparrow
    | GrayCatbird
    | GreatBlueHeron
    | GreatCrestedFlycatcher
    | GreatEgret
    | GreatHornedOwl
    | GreenHeron
    | HairyWoodpecker
    | HoodedWarbler
    | HornedLark
    | HouseFinch
    | HouseSparrow
    | IndigoBunting
    | KentuckyWarbler
    | Killdeer
    | LoggerheadShrike
    | LouisianaWaterthrush
    | Mallard
    | MourningDove
    | NorthernBobwhite
    | NorthernCardinal
    | NorthernFlicker
    | NorthernHouseWren
    | NorthernMockingbird
    | NorthernParula
    | NorthernRoughwingedSwallow
    | OrchardOriole
    | Osprey
    | Ovenbird
    | PileatedWoodpecker
    | PineWarbler
    | PrairieWarbler
    | ProthonotaryWarbler
    | PurpleMartin
    | RedbelliedWoodpecker
    | RedeyedVireo
    | RedheadedWoodpecker
    | RedshoulderedHawk
    | RedtailedHawk
    | RedwingedBlackbird
    | RockPigeon
    | RubythroatedHummingbird
    | ScarletTanager
    | SharpshinnedHawk
    | SongSparrow
    | SummerTanager
    | TreeSwallow
    | TuftedTitmouse
    | TurkeyVulture
    | WarblingVireo
    | WhitebreastedNuthatch
    | WhiteeyedVireo
    | WildTurkey
    | WoodDuck
    | WoodThrush
    | YellowWarbler
    | YellowbilledCuckoo
    | YellowbreastedChat
    | YellowthroatedVireo
    | YellowthroatedWarbler



-- All Species in a single list


allSpecies : List Species
allSpecies =
    [ AcadianFlycatcher
    , AmericanCrow
    , AmericanGoldfinch
    , AmericanRedstart
    , AmericanRobin
    , BaldEagle
    , BaltimoreOriole
    , BarnSwallow
    , BarredOwl
    , BeltedKingfisher
    , BlackVulture
    , BlackandwhiteWarbler
    , BlueGrosbeak
    , BlueJay
    , BluegrayGnatcatcher
    , BlueheadedVireo
    , BroadwingedHawk
    , BrownThrasher
    , BrownheadedCowbird
    , BrownheadedNuthatch
    , CanadaGoose
    , CarolinaChickadee
    , CarolinaWren
    , CedarWaxwing
    , ChimneySwift
    , ChippingSparrow
    , Chuckwillswidow
    , CliffSwallow
    , CommonGrackle
    , CommonNighthawk
    , CommonYellowthroat
    , CoopersHawk
    , Dickcissel
    , DoublecrestedCormorant
    , DownyWoodpecker
    , EasternBluebird
    , EasternKingbird
    , EasternMeadowlark
    , EasternPhoebe
    , EasternScreechOwl
    , EasternTowhee
    , EasternWhippoorwill
    , EasternWoodPewee
    , EuropeanStarling
    , FieldSparrow
    , FishCrow
    , GrasshopperSparrow
    , GrayCatbird
    , GreatBlueHeron
    , GreatCrestedFlycatcher
    , GreatEgret
    , GreatHornedOwl
    , GreenHeron
    , HairyWoodpecker
    , HoodedWarbler
    , HornedLark
    , HouseFinch
    , HouseSparrow
    , IndigoBunting
    , KentuckyWarbler
    , Killdeer
    , LoggerheadShrike
    , LouisianaWaterthrush
    , Mallard
    , MourningDove
    , NorthernBobwhite
    , NorthernCardinal
    , NorthernFlicker
    , NorthernHouseWren
    , NorthernMockingbird
    , NorthernParula
    , NorthernRoughwingedSwallow
    , OrchardOriole
    , Osprey
    , Ovenbird
    , PileatedWoodpecker
    , PineWarbler
    , PrairieWarbler
    , ProthonotaryWarbler
    , PurpleMartin
    , RedbelliedWoodpecker
    , RedeyedVireo
    , RedheadedWoodpecker
    , RedshoulderedHawk
    , RedtailedHawk
    , RedwingedBlackbird
    , RockPigeon
    , RubythroatedHummingbird
    , ScarletTanager
    , SharpshinnedHawk
    , SongSparrow
    , SummerTanager
    , TreeSwallow
    , TuftedTitmouse
    , TurkeyVulture
    , WarblingVireo
    , WhitebreastedNuthatch
    , WhiteeyedVireo
    , WildTurkey
    , WoodDuck
    , WoodThrush
    , YellowWarbler
    , YellowbilledCuckoo
    , YellowbreastedChat
    , YellowthroatedVireo
    , YellowthroatedWarbler
    ]



-- All Species records in a single list


allSpeciesRec : List SpeciesRec
allSpeciesRec =
    [ { species = AcadianFlycatcher
      , id = "AcadianFlycatcher"
      , commonName = "Acadian Flycatcher"
      , sciName = "Empidonax virescens"
      , rate = 0.063482270567
      , pvalue = 0.000000000001
      }
    , { species = AmericanCrow
      , id = "AmericanCrow"
      , commonName = "American Crow"
      , sciName = "Corvus brachyrhynchos"
      , rate = -0.008387511452
      , pvalue = 0.000262967062
      }
    , { species = AmericanGoldfinch
      , id = "AmericanGoldfinch"
      , commonName = "American Goldfinch"
      , sciName = "Spinus tristis"
      , rate = -0.030248302983
      , pvalue = 0.000000033486
      }
    , { species = AmericanRedstart
      , id = "AmericanRedstart"
      , commonName = "American Redstart"
      , sciName = "Setophaga ruticilla"
      , rate = -0.033032075429
      , pvalue = 0.358094189309
      }
    , { species = AmericanRobin
      , id = "AmericanRobin"
      , commonName = "American Robin"
      , sciName = "Turdus migratorius"
      , rate = -0.022616840988
      , pvalue = 0.001982368463
      }
    , { species = BaldEagle
      , id = "BaldEagle"
      , commonName = "Bald Eagle"
      , sciName = "Haliaeetus leucocephalus"
      , rate = 0.076687591087
      , pvalue = 0.207675863549
      }
    , { species = BaltimoreOriole
      , id = "BaltimoreOriole"
      , commonName = "Baltimore Oriole"
      , sciName = "Icterus galbula"
      , rate = 0.0
      , pvalue = 1.0
      }
    , { species = BarnSwallow
      , id = "BarnSwallow"
      , commonName = "Barn Swallow"
      , sciName = "Hirundo rustica"
      , rate = -0.023856142355
      , pvalue = 0.021959200253
      }
    , { species = BarredOwl
      , id = "BarredOwl"
      , commonName = "Barred Owl"
      , sciName = "Strix varia"
      , rate = 0.034666353886
      , pvalue = 0.006127926805
      }
    , { species = BeltedKingfisher
      , id = "BeltedKingfisher"
      , commonName = "Belted Kingfisher"
      , sciName = "Megaceryle alcyon"
      , rate = -0.062015257742
      , pvalue = 0.017681944217
      }
    , { species = BlackVulture
      , id = "BlackVulture"
      , commonName = "Black Vulture"
      , sciName = "Coragyps atratus"
      , rate = 0.059996795809
      , pvalue = 0.005952119263
      }
    , { species = BlackandwhiteWarbler
      , id = "BlackandwhiteWarbler"
      , commonName = "Black-and-white Warbler"
      , sciName = "Mniotilta varia"
      , rate = 0.058617175017
      , pvalue = 0.009637549841
      }
    , { species = BlueGrosbeak
      , id = "BlueGrosbeak"
      , commonName = "Blue Grosbeak"
      , sciName = "Passerina caerulea"
      , rate = 0.007851623421
      , pvalue = 0.299557869218
      }
    , { species = BlueJay
      , id = "BlueJay"
      , commonName = "Blue Jay"
      , sciName = "Cyanocitta cristata"
      , rate = -0.017459826441
      , pvalue = 0.000231399241
      }
    , { species = BluegrayGnatcatcher
      , id = "BluegrayGnatcatcher"
      , commonName = "Blue-gray Gnatcatcher"
      , sciName = "Polioptila caerulea"
      , rate = 0.009759260479
      , pvalue = 0.083241073067
      }
    , { species = BlueheadedVireo
      , id = "BlueheadedVireo"
      , commonName = "Blue-headed Vireo"
      , sciName = "Vireo solitarius"
      , rate = -0.060601682516
      , pvalue = 0.000009125482
      }
    , { species = BroadwingedHawk
      , id = "BroadwingedHawk"
      , commonName = "Broad-winged Hawk"
      , sciName = "Buteo platypterus"
      , rate = -0.1051552859
      , pvalue = 0.000000000004
      }
    , { species = BrownThrasher
      , id = "BrownThrasher"
      , commonName = "Brown Thrasher"
      , sciName = "Toxostoma rufum"
      , rate = -0.00091368419
      , pvalue = 0.882922685916
      }
    , { species = BrownheadedCowbird
      , id = "BrownheadedCowbird"
      , commonName = "Brown-headed Cowbird"
      , sciName = "Molothrus ater"
      , rate = 0.009588720953
      , pvalue = 0.141385119346
      }
    , { species = BrownheadedNuthatch
      , id = "BrownheadedNuthatch"
      , commonName = "Brown-headed Nuthatch"
      , sciName = "Sitta pusilla"
      , rate = 0.023186116226
      , pvalue = 0.076746222071
      }
    , { species = CanadaGoose
      , id = "CanadaGoose"
      , commonName = "Canada Goose"
      , sciName = "Branta canadensis"
      , rate = -0.029823782377
      , pvalue = 0.118983192925
      }
    , { species = CarolinaChickadee
      , id = "CarolinaChickadee"
      , commonName = "Carolina Chickadee"
      , sciName = "Poecile carolinensis"
      , rate = 0.0022666868
      , pvalue = 0.617669714454
      }
    , { species = CarolinaWren
      , id = "CarolinaWren"
      , commonName = "Carolina Wren"
      , sciName = "Thryothorus ludovicianus"
      , rate = 0.006805350107
      , pvalue = 0.047294465768
      }
    , { species = CedarWaxwing
      , id = "CedarWaxwing"
      , commonName = "Cedar Waxwing"
      , sciName = "Bombycilla cedrorum"
      , rate = -0.006991037177
      , pvalue = 0.777230665285
      }
    , { species = ChimneySwift
      , id = "ChimneySwift"
      , commonName = "Chimney Swift"
      , sciName = "Chaetura pelagica"
      , rate = -0.033673597758
      , pvalue = 0.00000060181
      }
    , { species = ChippingSparrow
      , id = "ChippingSparrow"
      , commonName = "Chipping Sparrow"
      , sciName = "Spizella passerina"
      , rate = 0.014777252169
      , pvalue = 0.001358841088
      }
    , { species = Chuckwillswidow
      , id = "Chuckwillswidow"
      , commonName = "Chuck-will's-widow"
      , sciName = "Antrostomus carolinensis"
      , rate = 0.009282880065
      , pvalue = 0.696655586418
      }
    , { species = CliffSwallow
      , id = "CliffSwallow"
      , commonName = "Cliff Swallow"
      , sciName = "Petrochelidon pyrrhonota"
      , rate = 0.235969799876
      , pvalue = 0.0
      }
    , { species = CommonGrackle
      , id = "CommonGrackle"
      , commonName = "Common Grackle"
      , sciName = "Quiscalus quiscula"
      , rate = -0.055599540751
      , pvalue = 0.000000001676
      }
    , { species = CommonNighthawk
      , id = "CommonNighthawk"
      , commonName = "Common Nighthawk"
      , sciName = "Chordeiles minor"
      , rate = 0.0
      , pvalue = 1.0
      }
    , { species = CommonYellowthroat
      , id = "CommonYellowthroat"
      , commonName = "Common Yellowthroat"
      , sciName = "Geothlypis trichas"
      , rate = -0.029858563229
      , pvalue = 0.000088937312
      }
    , { species = CoopersHawk
      , id = "CoopersHawk"
      , commonName = "Cooper's Hawk"
      , sciName = "Astur cooperii"
      , rate = 0.007834002886
      , pvalue = 0.654930844019
      }
    , { species = Dickcissel
      , id = "Dickcissel"
      , commonName = "Dickcissel"
      , sciName = "Spiza americana"
      , rate = 0.0
      , pvalue = 1.0
      }
    , { species = DoublecrestedCormorant
      , id = "DoublecrestedCormorant"
      , commonName = "Double-crested Cormorant"
      , sciName = "Nannopterum auritum"
      , rate = 0.024907932104
      , pvalue = 0.193205863516
      }
    , { species = DownyWoodpecker
      , id = "DownyWoodpecker"
      , commonName = "Downy Woodpecker"
      , sciName = "Dryobates pubescens"
      , rate = 0.012713806109
      , pvalue = 0.089386837697
      }
    , { species = EasternBluebird
      , id = "EasternBluebird"
      , commonName = "Eastern Bluebird"
      , sciName = "Sialia sialis"
      , rate = -0.001216535053
      , pvalue = 0.715148371466
      }
    , { species = EasternKingbird
      , id = "EasternKingbird"
      , commonName = "Eastern Kingbird"
      , sciName = "Tyrannus tyrannus"
      , rate = -0.015891428177
      , pvalue = 0.12232230668
      }
    , { species = EasternMeadowlark
      , id = "EasternMeadowlark"
      , commonName = "Eastern Meadowlark"
      , sciName = "Sturnella magna"
      , rate = -0.028455442177
      , pvalue = 0.00124453176
      }
    , { species = EasternPhoebe
      , id = "EasternPhoebe"
      , commonName = "Eastern Phoebe"
      , sciName = "Sayornis phoebe"
      , rate = 0.012185388277
      , pvalue = 0.020391511365
      }
    , { species = EasternScreechOwl
      , id = "EasternScreechOwl"
      , commonName = "Eastern Screech-Owl"
      , sciName = "Megascops asio"
      , rate = 0.0795172908
      , pvalue = 0.321379163585
      }
    , { species = EasternTowhee
      , id = "EasternTowhee"
      , commonName = "Eastern Towhee"
      , sciName = "Pipilo erythrophthalmus"
      , rate = -0.032217964851
      , pvalue = 0.0
      }
    , { species = EasternWhippoorwill
      , id = "EasternWhippoorwill"
      , commonName = "Eastern Whip-poor-will"
      , sciName = "Antrostomus vociferus"
      , rate = -0.049850159988
      , pvalue = 0.002381902776
      }
    , { species = EasternWoodPewee
      , id = "EasternWoodPewee"
      , commonName = "Eastern Wood-Pewee"
      , sciName = "Contopus virens"
      , rate = -0.004748353112
      , pvalue = 0.389098802159
      }
    , { species = EuropeanStarling
      , id = "EuropeanStarling"
      , commonName = "European Starling"
      , sciName = "Sturnus vulgaris"
      , rate = -0.032630167434
      , pvalue = 0.001816028355
      }
    , { species = FieldSparrow
      , id = "FieldSparrow"
      , commonName = "Field Sparrow"
      , sciName = "Spizella pusilla"
      , rate = -0.044154671485
      , pvalue = 0.000962978577
      }
    , { species = FishCrow
      , id = "FishCrow"
      , commonName = "Fish Crow"
      , sciName = "Corvus ossifragus"
      , rate = 0.060638508655
      , pvalue = 0.0
      }
    , { species = GrasshopperSparrow
      , id = "GrasshopperSparrow"
      , commonName = "Grasshopper Sparrow"
      , sciName = "Ammodramus savannarum"
      , rate = -0.007650969207
      , pvalue = 0.706999459014
      }
    , { species = GrayCatbird
      , id = "GrayCatbird"
      , commonName = "Gray Catbird"
      , sciName = "Dumetella carolinensis"
      , rate = -0.012352031857
      , pvalue = 0.129128619683
      }
    , { species = GreatBlueHeron
      , id = "GreatBlueHeron"
      , commonName = "Great Blue Heron"
      , sciName = "Ardea herodias"
      , rate = 0.00960889705
      , pvalue = 0.301409661286
      }
    , { species = GreatCrestedFlycatcher
      , id = "GreatCrestedFlycatcher"
      , commonName = "Great Crested Flycatcher"
      , sciName = "Myiarchus crinitus"
      , rate = 0.035877726437
      , pvalue = 0.000003146758
      }
    , { species = GreatEgret
      , id = "GreatEgret"
      , commonName = "Great Egret"
      , sciName = "Ardea alba"
      , rate = 0.0
      , pvalue = 1.0
      }
    , { species = GreatHornedOwl
      , id = "GreatHornedOwl"
      , commonName = "Great Horned Owl"
      , sciName = "Bubo virginianus"
      , rate = -0.004357526622
      , pvalue = 0.873915748522
      }
    , { species = GreenHeron
      , id = "GreenHeron"
      , commonName = "Green Heron"
      , sciName = "Butorides virescens"
      , rate = -0.037976770852
      , pvalue = 0.020722912762
      }
    , { species = HairyWoodpecker
      , id = "HairyWoodpecker"
      , commonName = "Hairy Woodpecker"
      , sciName = "Dryobates villosus"
      , rate = -0.005288613798
      , pvalue = 0.727378938859
      }
    , { species = HoodedWarbler
      , id = "HoodedWarbler"
      , commonName = "Hooded Warbler"
      , sciName = "Setophaga citrina"
      , rate = 0.025092680506
      , pvalue = 0.000075307919
      }
    , { species = HornedLark
      , id = "HornedLark"
      , commonName = "Horned Lark"
      , sciName = "Eremophila alpestris"
      , rate = 0.0
      , pvalue = 1.0
      }
    , { species = HouseFinch
      , id = "HouseFinch"
      , commonName = "House Finch"
      , sciName = "Haemorhous mexicanus"
      , rate = 0.007002091926
      , pvalue = 0.352129480617
      }
    , { species = HouseSparrow
      , id = "HouseSparrow"
      , commonName = "House Sparrow"
      , sciName = "Passer domesticus"
      , rate = -0.07952746259
      , pvalue = 0.000000449887
      }
    , { species = IndigoBunting
      , id = "IndigoBunting"
      , commonName = "Indigo Bunting"
      , sciName = "Passerina cyanea"
      , rate = -0.027505192786
      , pvalue = 0.000000000042
      }
    , { species = KentuckyWarbler
      , id = "KentuckyWarbler"
      , commonName = "Kentucky Warbler"
      , sciName = "Geothlypis formosa"
      , rate = 0.026337142625
      , pvalue = 0.435143493108
      }
    , { species = Killdeer
      , id = "Killdeer"
      , commonName = "Killdeer"
      , sciName = "Charadrius vociferus"
      , rate = -0.021520329362
      , pvalue = 0.115981946133
      }
    , { species = LoggerheadShrike
      , id = "LoggerheadShrike"
      , commonName = "Loggerhead Shrike"
      , sciName = "Lanius ludovicianus"
      , rate = 0.008075689661
      , pvalue = 0.910026597635
      }
    , { species = LouisianaWaterthrush
      , id = "LouisianaWaterthrush"
      , commonName = "Louisiana Waterthrush"
      , sciName = "Parkesia motacilla"
      , rate = 0.027404750294
      , pvalue = 0.169593095966
      }
    , { species = Mallard
      , id = "Mallard"
      , commonName = "Mallard"
      , sciName = "Anas platyrhynchos"
      , rate = -0.035609436452
      , pvalue = 0.060115905974
      }
    , { species = MourningDove
      , id = "MourningDove"
      , commonName = "Mourning Dove"
      , sciName = "Zenaida macroura"
      , rate = -0.011728310617
      , pvalue = 0.002884657124
      }
    , { species = NorthernBobwhite
      , id = "NorthernBobwhite"
      , commonName = "Northern Bobwhite"
      , sciName = "Colinus virginianus"
      , rate = -0.116061345773
      , pvalue = 0.000000000413
      }
    , { species = NorthernCardinal
      , id = "NorthernCardinal"
      , commonName = "Northern Cardinal"
      , sciName = "Cardinalis cardinalis"
      , rate = -0.004971037161
      , pvalue = 0.040133701253
      }
    , { species = NorthernFlicker
      , id = "NorthernFlicker"
      , commonName = "Northern Flicker"
      , sciName = "Colaptes auratus"
      , rate = -0.043037313911
      , pvalue = 0.001893509949
      }
    , { species = NorthernHouseWren
      , id = "NorthernHouseWren"
      , commonName = "Northern House Wren"
      , sciName = "Troglodytes aedon"
      , rate = -0.046080279815
      , pvalue = 0.004774829266
      }
    , { species = NorthernMockingbird
      , id = "NorthernMockingbird"
      , commonName = "Northern Mockingbird"
      , sciName = "Mimus polyglottos"
      , rate = -0.010224718717
      , pvalue = 0.011935581434
      }
    , { species = NorthernParula
      , id = "NorthernParula"
      , commonName = "Northern Parula"
      , sciName = "Setophaga americana"
      , rate = 0.037861331705
      , pvalue = 0.003667342115
      }
    , { species = NorthernRoughwingedSwallow
      , id = "NorthernRoughwingedSwallow"
      , commonName = "Northern Rough-winged Swallow"
      , sciName = "Stelgidopteryx serripennis"
      , rate = 0.008621780739
      , pvalue = 0.759775974764
      }
    , { species = OrchardOriole
      , id = "OrchardOriole"
      , commonName = "Orchard Oriole"
      , sciName = "Icterus spurius"
      , rate = -0.020459873736
      , pvalue = 0.082636058822
      }
    , { species = Osprey
      , id = "Osprey"
      , commonName = "Osprey"
      , sciName = "Pandion haliaetus"
      , rate = 0.063630638143
      , pvalue = 0.000100846483
      }
    , { species = Ovenbird
      , id = "Ovenbird"
      , commonName = "Ovenbird"
      , sciName = "Seiurus aurocapilla"
      , rate = 0.001155967735
      , pvalue = 0.758508236766
      }
    , { species = PileatedWoodpecker
      , id = "PileatedWoodpecker"
      , commonName = "Pileated Woodpecker"
      , sciName = "Dryocopus pileatus"
      , rate = 0.037507715659
      , pvalue = 0.001400142851
      }
    , { species = PineWarbler
      , id = "PineWarbler"
      , commonName = "Pine Warbler"
      , sciName = "Setophaga pinus"
      , rate = -0.004558399232
      , pvalue = 0.299466787818
      }
    , { species = PrairieWarbler
      , id = "PrairieWarbler"
      , commonName = "Prairie Warbler"
      , sciName = "Setophaga discolor"
      , rate = -0.042479742295
      , pvalue = 0.000000000655
      }
    , { species = ProthonotaryWarbler
      , id = "ProthonotaryWarbler"
      , commonName = "Prothonotary Warbler"
      , sciName = "Protonotaria citrea"
      , rate = 0.026814784572
      , pvalue = 0.377662274511
      }
    , { species = PurpleMartin
      , id = "PurpleMartin"
      , commonName = "Purple Martin"
      , sciName = "Progne subis"
      , rate = 0.009694483661
      , pvalue = 0.234343080345
      }
    , { species = RedbelliedWoodpecker
      , id = "RedbelliedWoodpecker"
      , commonName = "Red-bellied Woodpecker"
      , sciName = "Melanerpes carolinus"
      , rate = 0.003152773536
      , pvalue = 0.39886602639
      }
    , { species = RedeyedVireo
      , id = "RedeyedVireo"
      , commonName = "Red-eyed Vireo"
      , sciName = "Vireo olivaceus"
      , rate = -0.008715439524
      , pvalue = 0.102472443485
      }
    , { species = RedheadedWoodpecker
      , id = "RedheadedWoodpecker"
      , commonName = "Red-headed Woodpecker"
      , sciName = "Melanerpes erythrocephalus"
      , rate = 0.014522476163
      , pvalue = 0.3728181476
      }
    , { species = RedshoulderedHawk
      , id = "RedshoulderedHawk"
      , commonName = "Red-shouldered Hawk"
      , sciName = "Buteo lineatus"
      , rate = 0.050309162745
      , pvalue = 0.000000000983
      }
    , { species = RedtailedHawk
      , id = "RedtailedHawk"
      , commonName = "Red-tailed Hawk"
      , sciName = "Buteo jamaicensis"
      , rate = 0.00520415168
      , pvalue = 0.66933282848
      }
    , { species = RedwingedBlackbird
      , id = "RedwingedBlackbird"
      , commonName = "Red-winged Blackbird"
      , sciName = "Agelaius phoeniceus"
      , rate = -0.029423061812
      , pvalue = 0.006644921856
      }
    , { species = RockPigeon
      , id = "RockPigeon"
      , commonName = "Rock Pigeon"
      , sciName = "Columba livia"
      , rate = -0.047078242103
      , pvalue = 0.012472512495
      }
    , { species = RubythroatedHummingbird
      , id = "RubythroatedHummingbird"
      , commonName = "Ruby-throated Hummingbird"
      , sciName = "Archilochus colubris"
      , rate = -0.03626707568
      , pvalue = 0.000181886959
      }
    , { species = ScarletTanager
      , id = "ScarletTanager"
      , commonName = "Scarlet Tanager"
      , sciName = "Piranga olivacea"
      , rate = -0.041252105928
      , pvalue = 0.000000005837
      }
    , { species = SharpshinnedHawk
      , id = "SharpshinnedHawk"
      , commonName = "Sharp-shinned Hawk"
      , sciName = "Accipiter striatus"
      , rate = -0.063416729936
      , pvalue = 0.068498414161
      }
    , { species = SongSparrow
      , id = "SongSparrow"
      , commonName = "Song Sparrow"
      , sciName = "Melospiza melodia"
      , rate = 0.02793428842
      , pvalue = 0.041314124741
      }
    , { species = SummerTanager
      , id = "SummerTanager"
      , commonName = "Summer Tanager"
      , sciName = "Piranga rubra"
      , rate = 0.024308827692
      , pvalue = 0.000037302054
      }
    , { species = TreeSwallow
      , id = "TreeSwallow"
      , commonName = "Tree Swallow"
      , sciName = "Tachycineta bicolor"
      , rate = 0.108494695302
      , pvalue = 0.000086518412
      }
    , { species = TuftedTitmouse
      , id = "TuftedTitmouse"
      , commonName = "Tufted Titmouse"
      , sciName = "Baeolophus bicolor"
      , rate = 0.005583450259
      , pvalue = 0.124226559731
      }
    , { species = TurkeyVulture
      , id = "TurkeyVulture"
      , commonName = "Turkey Vulture"
      , sciName = "Cathartes aura"
      , rate = 0.00365328303
      , pvalue = 0.807660640593
      }
    , { species = WarblingVireo
      , id = "WarblingVireo"
      , commonName = "Warbling Vireo"
      , sciName = "Vireo gilvus"
      , rate = -0.163806631998
      , pvalue = 0.020528358432
      }
    , { species = WhitebreastedNuthatch
      , id = "WhitebreastedNuthatch"
      , commonName = "White-breasted Nuthatch"
      , sciName = "Sitta carolinensis"
      , rate = 0.020307699845
      , pvalue = 0.022894358284
      }
    , { species = WhiteeyedVireo
      , id = "WhiteeyedVireo"
      , commonName = "White-eyed Vireo"
      , sciName = "Vireo griseus"
      , rate = 0.070944013403
      , pvalue = 0.000000000042
      }
    , { species = WildTurkey
      , id = "WildTurkey"
      , commonName = "Wild Turkey"
      , sciName = "Meleagris gallopavo"
      , rate = 0.049788998578
      , pvalue = 0.001880555987
      }
    , { species = WoodDuck
      , id = "WoodDuck"
      , commonName = "Wood Duck"
      , sciName = "Aix sponsa"
      , rate = -0.002060464469
      , pvalue = 0.939247044667
      }
    , { species = WoodThrush
      , id = "WoodThrush"
      , commonName = "Wood Thrush"
      , sciName = "Hylocichla mustelina"
      , rate = -0.058946829526
      , pvalue = 0.0
      }
    , { species = YellowWarbler
      , id = "YellowWarbler"
      , commonName = "Yellow Warbler"
      , sciName = "Setophaga petechia"
      , rate = 0.020965465031
      , pvalue = 0.507991345288
      }
    , { species = YellowbilledCuckoo
      , id = "YellowbilledCuckoo"
      , commonName = "Yellow-billed Cuckoo"
      , sciName = "Coccyzus americanus"
      , rate = 0.011829653187
      , pvalue = 0.03555614426
      }
    , { species = YellowbreastedChat
      , id = "YellowbreastedChat"
      , commonName = "Yellow-breasted Chat"
      , sciName = "Icteria virens"
      , rate = -0.039112212193
      , pvalue = 0.000000155975
      }
    , { species = YellowthroatedVireo
      , id = "YellowthroatedVireo"
      , commonName = "Yellow-throated Vireo"
      , sciName = "Vireo flavifrons"
      , rate = -0.000766412456
      , pvalue = 0.953647464237
      }
    , { species = YellowthroatedWarbler
      , id = "YellowthroatedWarbler"
      , commonName = "Yellow-throated Warbler"
      , sciName = "Setophaga dominica"
      , rate = 0.074795266867
      , pvalue = 0.000000009609
      }
    ]



-- Convert species to its common name as a String.


speciesToString : Species -> String
speciesToString species =
    case species of
        AcadianFlycatcher ->
            "Acadian Flycatcher"

        AmericanCrow ->
            "American Crow"

        AmericanGoldfinch ->
            "American Goldfinch"

        AmericanRedstart ->
            "American Redstart"

        AmericanRobin ->
            "American Robin"

        BaldEagle ->
            "Bald Eagle"

        BaltimoreOriole ->
            "Baltimore Oriole"

        BarnSwallow ->
            "Barn Swallow"

        BarredOwl ->
            "Barred Owl"

        BeltedKingfisher ->
            "Belted Kingfisher"

        BlackVulture ->
            "Black Vulture"

        BlackandwhiteWarbler ->
            "Black-and-white Warbler"

        BlueGrosbeak ->
            "Blue Grosbeak"

        BlueJay ->
            "Blue Jay"

        BluegrayGnatcatcher ->
            "Blue-gray Gnatcatcher"

        BlueheadedVireo ->
            "Blue-headed Vireo"

        BroadwingedHawk ->
            "Broad-winged Hawk"

        BrownThrasher ->
            "Brown Thrasher"

        BrownheadedCowbird ->
            "Brown-headed Cowbird"

        BrownheadedNuthatch ->
            "Brown-headed Nuthatch"

        CanadaGoose ->
            "Canada Goose"

        CarolinaChickadee ->
            "Carolina Chickadee"

        CarolinaWren ->
            "Carolina Wren"

        CedarWaxwing ->
            "Cedar Waxwing"

        ChimneySwift ->
            "Chimney Swift"

        ChippingSparrow ->
            "Chipping Sparrow"

        Chuckwillswidow ->
            "Chuck-will's-widow"

        CliffSwallow ->
            "Cliff Swallow"

        CommonGrackle ->
            "Common Grackle"

        CommonNighthawk ->
            "Common Nighthawk"

        CommonYellowthroat ->
            "Common Yellowthroat"

        CoopersHawk ->
            "Cooper's Hawk"

        Dickcissel ->
            "Dickcissel"

        DoublecrestedCormorant ->
            "Double-crested Cormorant"

        DownyWoodpecker ->
            "Downy Woodpecker"

        EasternBluebird ->
            "Eastern Bluebird"

        EasternKingbird ->
            "Eastern Kingbird"

        EasternMeadowlark ->
            "Eastern Meadowlark"

        EasternPhoebe ->
            "Eastern Phoebe"

        EasternScreechOwl ->
            "Eastern Screech-Owl"

        EasternTowhee ->
            "Eastern Towhee"

        EasternWhippoorwill ->
            "Eastern Whip-poor-will"

        EasternWoodPewee ->
            "Eastern Wood-Pewee"

        EuropeanStarling ->
            "European Starling"

        FieldSparrow ->
            "Field Sparrow"

        FishCrow ->
            "Fish Crow"

        GrasshopperSparrow ->
            "Grasshopper Sparrow"

        GrayCatbird ->
            "Gray Catbird"

        GreatBlueHeron ->
            "Great Blue Heron"

        GreatCrestedFlycatcher ->
            "Great Crested Flycatcher"

        GreatEgret ->
            "Great Egret"

        GreatHornedOwl ->
            "Great Horned Owl"

        GreenHeron ->
            "Green Heron"

        HairyWoodpecker ->
            "Hairy Woodpecker"

        HoodedWarbler ->
            "Hooded Warbler"

        HornedLark ->
            "Horned Lark"

        HouseFinch ->
            "House Finch"

        HouseSparrow ->
            "House Sparrow"

        IndigoBunting ->
            "Indigo Bunting"

        KentuckyWarbler ->
            "Kentucky Warbler"

        Killdeer ->
            "Killdeer"

        LoggerheadShrike ->
            "Loggerhead Shrike"

        LouisianaWaterthrush ->
            "Louisiana Waterthrush"

        Mallard ->
            "Mallard"

        MourningDove ->
            "Mourning Dove"

        NorthernBobwhite ->
            "Northern Bobwhite"

        NorthernCardinal ->
            "Northern Cardinal"

        NorthernFlicker ->
            "Northern Flicker"

        NorthernHouseWren ->
            "Northern House Wren"

        NorthernMockingbird ->
            "Northern Mockingbird"

        NorthernParula ->
            "Northern Parula"

        NorthernRoughwingedSwallow ->
            "Northern Rough-winged Swallow"

        OrchardOriole ->
            "Orchard Oriole"

        Osprey ->
            "Osprey"

        Ovenbird ->
            "Ovenbird"

        PileatedWoodpecker ->
            "Pileated Woodpecker"

        PineWarbler ->
            "Pine Warbler"

        PrairieWarbler ->
            "Prairie Warbler"

        ProthonotaryWarbler ->
            "Prothonotary Warbler"

        PurpleMartin ->
            "Purple Martin"

        RedbelliedWoodpecker ->
            "Red-bellied Woodpecker"

        RedeyedVireo ->
            "Red-eyed Vireo"

        RedheadedWoodpecker ->
            "Red-headed Woodpecker"

        RedshoulderedHawk ->
            "Red-shouldered Hawk"

        RedtailedHawk ->
            "Red-tailed Hawk"

        RedwingedBlackbird ->
            "Red-winged Blackbird"

        RockPigeon ->
            "Rock Pigeon"

        RubythroatedHummingbird ->
            "Ruby-throated Hummingbird"

        ScarletTanager ->
            "Scarlet Tanager"

        SharpshinnedHawk ->
            "Sharp-shinned Hawk"

        SongSparrow ->
            "Song Sparrow"

        SummerTanager ->
            "Summer Tanager"

        TreeSwallow ->
            "Tree Swallow"

        TuftedTitmouse ->
            "Tufted Titmouse"

        TurkeyVulture ->
            "Turkey Vulture"

        WarblingVireo ->
            "Warbling Vireo"

        WhitebreastedNuthatch ->
            "White-breasted Nuthatch"

        WhiteeyedVireo ->
            "White-eyed Vireo"

        WildTurkey ->
            "Wild Turkey"

        WoodDuck ->
            "Wood Duck"

        WoodThrush ->
            "Wood Thrush"

        YellowWarbler ->
            "Yellow Warbler"

        YellowbilledCuckoo ->
            "Yellow-billed Cuckoo"

        YellowbreastedChat ->
            "Yellow-breasted Chat"

        YellowthroatedVireo ->
            "Yellow-throated Vireo"

        YellowthroatedWarbler ->
            "Yellow-throated Warbler"



-- Identify a Species by a string, maybe


stringToSpecies : String -> Maybe Species
stringToSpecies s =
    List.map (\x -> ( x, speciesToString x )) allSpecies
        |> List.filterMap
            (\( x, y ) ->
                if y == s then
                    Just x

                else
                    Nothing
            )
        |> List.head



-- Get the SpeciesRec for a Species


lookupSpecies : Species -> Maybe SpeciesRec
lookupSpecies x =
    List.filter (\r -> x == r.species) allSpeciesRec
        |> List.head
