{-
   Elm code generated by prepare_results.R
   This file should not be modified except by code formatters.
-}


module Data.Species exposing (..)

-- A record containing information and data about an individual species


type alias SpeciesRec =
    { species : Species
    , id : String
    , commonName : String
    , sciName : String
    , rate : Float
    , pvalue : Float
    }



-- Enumeration of all species observed in MBBS.


type Species
    = AcadianFlycatcher
    | AmericanCrow
    | AmericanGoldfinch
    | AmericanRedstart
    | AmericanRobin
    | BaldEagle
    | BaltimoreOriole
    | BarnSwallow
    | BarredOwl
    | BeltedKingfisher
    | BlackVulture
    | BlackandwhiteWarbler
    | BlueGrosbeak
    | BlueJay
    | BluegrayGnatcatcher
    | BlueheadedVireo
    | BroadwingedHawk
    | BrownThrasher
    | BrownheadedCowbird
    | BrownheadedNuthatch
    | CanadaGoose
    | CarolinaChickadee
    | CarolinaWren
    | CedarWaxwing
    | ChimneySwift
    | Chuckwillswidow
    | CliffSwallow
    | CommonGrackle
    | CommonYellowthroat
    | CoopersHawk
    | Dickcissel
    | DoublecrestedCormorant
    | DownyWoodpecker
    | EasternBluebird
    | EasternKingbird
    | EasternMeadowlark
    | EasternPhoebe
    | EasternScreechOwl
    | EasternTowhee
    | EasternWhippoorwill
    | EasternWoodPewee
    | EuropeanStarling
    | FieldSparrow
    | FishCrow
    | GrasshopperSparrow
    | GrayCatbird
    | GreatBlueHeron
    | GreatCrestedFlycatcher
    | GreatEgret
    | GreatHornedOwl
    | GreenHeron
    | HairyWoodpecker
    | HoodedWarbler
    | HornedLark
    | HouseFinch
    | HouseSparrow
    | HouseWren
    | IndigoBunting
    | KentuckyWarbler
    | Killdeer
    | LoggerheadShrike
    | LouisianaWaterthrush
    | Mallard
    | MourningDove
    | NorthernBobwhite
    | NorthernCardinal
    | NorthernFlicker
    | NorthernMockingbird
    | NorthernParula
    | NorthernRoughwingedSwallow
    | OrchardOriole
    | Osprey
    | Ovenbird
    | PileatedWoodpecker
    | PrairieWarbler
    | ProthonotaryWarbler
    | PurpleMartin
    | RedbelliedWoodpecker
    | RedeyedVireo
    | RedheadedWoodpecker
    | RedshoulderedHawk
    | RedtailedHawk
    | RedwingedBlackbird
    | RockPigeon
    | RubythroatedHummingbird
    | ScarletTanager
    | SharpshinnedHawk
    | SongSparrow
    | SummerTanager
    | TreeSwallow
    | TuftedTitmouse
    | TurkeyVulture
    | WarblingVireo
    | WhitebreastedNuthatch
    | WhiteeyedVireo
    | WildTurkey
    | WoodDuck
    | WoodThrush
    | YellowWarbler
    | YellowbilledCuckoo
    | YellowbreastedChat
    | YellowthroatedVireo
    | YellowthroatedWarbler



-- All Species in a single list


allSpecies : List Species
allSpecies =
    [ AcadianFlycatcher
    , AmericanCrow
    , AmericanGoldfinch
    , AmericanRedstart
    , AmericanRobin
    , BaldEagle
    , BaltimoreOriole
    , BarnSwallow
    , BarredOwl
    , BeltedKingfisher
    , BlackVulture
    , BlackandwhiteWarbler
    , BlueGrosbeak
    , BlueJay
    , BluegrayGnatcatcher
    , BlueheadedVireo
    , BroadwingedHawk
    , BrownThrasher
    , BrownheadedCowbird
    , BrownheadedNuthatch
    , CanadaGoose
    , CarolinaChickadee
    , CarolinaWren
    , CedarWaxwing
    , ChimneySwift
    , Chuckwillswidow
    , CliffSwallow
    , CommonGrackle
    , CommonYellowthroat
    , CoopersHawk
    , Dickcissel
    , DoublecrestedCormorant
    , DownyWoodpecker
    , EasternBluebird
    , EasternKingbird
    , EasternMeadowlark
    , EasternPhoebe
    , EasternScreechOwl
    , EasternTowhee
    , EasternWhippoorwill
    , EasternWoodPewee
    , EuropeanStarling
    , FieldSparrow
    , FishCrow
    , GrasshopperSparrow
    , GrayCatbird
    , GreatBlueHeron
    , GreatCrestedFlycatcher
    , GreatEgret
    , GreatHornedOwl
    , GreenHeron
    , HairyWoodpecker
    , HoodedWarbler
    , HornedLark
    , HouseFinch
    , HouseSparrow
    , HouseWren
    , IndigoBunting
    , KentuckyWarbler
    , Killdeer
    , LoggerheadShrike
    , LouisianaWaterthrush
    , Mallard
    , MourningDove
    , NorthernBobwhite
    , NorthernCardinal
    , NorthernFlicker
    , NorthernMockingbird
    , NorthernParula
    , NorthernRoughwingedSwallow
    , OrchardOriole
    , Osprey
    , Ovenbird
    , PileatedWoodpecker
    , PrairieWarbler
    , ProthonotaryWarbler
    , PurpleMartin
    , RedbelliedWoodpecker
    , RedeyedVireo
    , RedheadedWoodpecker
    , RedshoulderedHawk
    , RedtailedHawk
    , RedwingedBlackbird
    , RockPigeon
    , RubythroatedHummingbird
    , ScarletTanager
    , SharpshinnedHawk
    , SongSparrow
    , SummerTanager
    , TreeSwallow
    , TuftedTitmouse
    , TurkeyVulture
    , WarblingVireo
    , WhitebreastedNuthatch
    , WhiteeyedVireo
    , WildTurkey
    , WoodDuck
    , WoodThrush
    , YellowWarbler
    , YellowbilledCuckoo
    , YellowbreastedChat
    , YellowthroatedVireo
    , YellowthroatedWarbler
    ]



-- All Species records in a single list


allSpeciesRec : List SpeciesRec
allSpeciesRec =
    [ { species = AcadianFlycatcher
      , id = "AcadianFlycatcher"
      , commonName = "Acadian Flycatcher"
      , sciName = "Empidonax virescens"
      , rate = 0.058421030325
      , pvalue = 0.000000039428
      }
    , { species = AmericanCrow
      , id = "AmericanCrow"
      , commonName = "American Crow"
      , sciName = "Corvus brachyrhynchos"
      , rate = -0.007050178818
      , pvalue = 0.012016636945
      }
    , { species = AmericanGoldfinch
      , id = "AmericanGoldfinch"
      , commonName = "American Goldfinch"
      , sciName = "Spinus tristis"
      , rate = -0.030696905089
      , pvalue = 0.000061614066
      }
    , { species = AmericanRedstart
      , id = "AmericanRedstart"
      , commonName = "American Redstart"
      , sciName = "Setophaga ruticilla"
      , rate = -0.048616181767
      , pvalue = 0.217451068881
      }
    , { species = AmericanRobin
      , id = "AmericanRobin"
      , commonName = "American Robin"
      , sciName = "Turdus migratorius"
      , rate = -0.017329419688
      , pvalue = 0.025386938404
      }
    , { species = BaldEagle
      , id = "BaldEagle"
      , commonName = "Bald Eagle"
      , sciName = "Haliaeetus leucocephalus"
      , rate = 0.080212552979
      , pvalue = 0.25368041893
      }
    , { species = BaltimoreOriole
      , id = "BaltimoreOriole"
      , commonName = "Baltimore Oriole"
      , sciName = "Icterus galbula"
      , rate = 0.02806515625
      , pvalue = 0.811456331425
      }
    , { species = BarnSwallow
      , id = "BarnSwallow"
      , commonName = "Barn Swallow"
      , sciName = "Hirundo rustica"
      , rate = -0.021445273202
      , pvalue = 0.102350834243
      }
    , { species = BarredOwl
      , id = "BarredOwl"
      , commonName = "Barred Owl"
      , sciName = "Strix varia"
      , rate = 0.026448048948
      , pvalue = 0.075221358218
      }
    , { species = BeltedKingfisher
      , id = "BeltedKingfisher"
      , commonName = "Belted Kingfisher"
      , sciName = "Megaceryle alcyon"
      , rate = -0.048811074598
      , pvalue = 0.132626373091
      }
    , { species = BlackVulture
      , id = "BlackVulture"
      , commonName = "Black Vulture"
      , sciName = "Coragyps atratus"
      , rate = 0.076097143449
      , pvalue = 0.000904658579
      }
    , { species = BlackandwhiteWarbler
      , id = "BlackandwhiteWarbler"
      , commonName = "Black-and-white Warbler"
      , sciName = "Mniotilta varia"
      , rate = 0.038411981686
      , pvalue = 0.074691996039
      }
    , { species = BlueGrosbeak
      , id = "BlueGrosbeak"
      , commonName = "Blue Grosbeak"
      , sciName = "Passerina caerulea"
      , rate = 0.007638539511
      , pvalue = 0.427920775064
      }
    , { species = BlueJay
      , id = "BlueJay"
      , commonName = "Blue Jay"
      , sciName = "Cyanocitta cristata"
      , rate = -0.015543883566
      , pvalue = 0.012385431928
      }
    , { species = BluegrayGnatcatcher
      , id = "BluegrayGnatcatcher"
      , commonName = "Blue-gray Gnatcatcher"
      , sciName = "Polioptila caerulea"
      , rate = 0.007546473789
      , pvalue = 0.255211097046
      }
    , { species = BlueheadedVireo
      , id = "BlueheadedVireo"
      , commonName = "Blue-headed Vireo"
      , sciName = "Vireo solitarius"
      , rate = -0.039291508291
      , pvalue = 0.016524216224
      }
    , { species = BroadwingedHawk
      , id = "BroadwingedHawk"
      , commonName = "Broad-winged Hawk"
      , sciName = "Buteo platypterus"
      , rate = -0.091599407413
      , pvalue = 0.000000142044
      }
    , { species = BrownThrasher
      , id = "BrownThrasher"
      , commonName = "Brown Thrasher"
      , sciName = "Toxostoma rufum"
      , rate = 0.005897077165
      , pvalue = 0.44529740655
      }
    , { species = BrownheadedCowbird
      , id = "BrownheadedCowbird"
      , commonName = "Brown-headed Cowbird"
      , sciName = "Molothrus ater"
      , rate = 0.011822443344
      , pvalue = 0.147028784891
      }
    , { species = BrownheadedNuthatch
      , id = "BrownheadedNuthatch"
      , commonName = "Brown-headed Nuthatch"
      , sciName = "Sitta pusilla"
      , rate = 0.011630492577
      , pvalue = 0.456218351755
      }
    , { species = CanadaGoose
      , id = "CanadaGoose"
      , commonName = "Canada Goose"
      , sciName = "Branta canadensis"
      , rate = -0.036877674167
      , pvalue = 0.096631803642
      }
    , { species = CarolinaChickadee
      , id = "CarolinaChickadee"
      , commonName = "Carolina Chickadee"
      , sciName = "Poecile carolinensis"
      , rate = 0.002031731854
      , pvalue = 0.736911575122
      }
    , { species = CarolinaWren
      , id = "CarolinaWren"
      , commonName = "Carolina Wren"
      , sciName = "Thryothorus ludovicianus"
      , rate = 0.008703975698
      , pvalue = 0.01479076674
      }
    , { species = CedarWaxwing
      , id = "CedarWaxwing"
      , commonName = "Cedar Waxwing"
      , sciName = "Bombycilla cedrorum"
      , rate = -0.022593290215
      , pvalue = 0.256324702266
      }
    , { species = ChimneySwift
      , id = "ChimneySwift"
      , commonName = "Chimney Swift"
      , sciName = "Chaetura pelagica"
      , rate = -0.034503014457
      , pvalue = 0.000397312223
      }
    , { species = Chuckwillswidow
      , id = "Chuckwillswidow"
      , commonName = "Chuck-will's-widow"
      , sciName = "Antrostomus carolinensis"
      , rate = 0.02389125939
      , pvalue = 0.097458193376
      }
    , { species = CliffSwallow
      , id = "CliffSwallow"
      , commonName = "Cliff Swallow"
      , sciName = "Petrochelidon pyrrhonota"
      , rate = 0.119248145008
      , pvalue = 0.0
      }
    , { species = CommonGrackle
      , id = "CommonGrackle"
      , commonName = "Common Grackle"
      , sciName = "Quiscalus quiscula"
      , rate = -0.053569704268
      , pvalue = 0.000000024633
      }
    , { species = CommonYellowthroat
      , id = "CommonYellowthroat"
      , commonName = "Common Yellowthroat"
      , sciName = "Geothlypis trichas"
      , rate = -0.029952764147
      , pvalue = 0.002162733022
      }
    , { species = CoopersHawk
      , id = "CoopersHawk"
      , commonName = "Cooper's Hawk"
      , sciName = "Accipiter cooperii"
      , rate = -0.003406367518
      , pvalue = 0.886913391604
      }
    , { species = Dickcissel
      , id = "Dickcissel"
      , commonName = "Dickcissel"
      , sciName = "Spiza americana"
      , rate = 0.127154501907
      , pvalue = 0.375352071642
      }
    , { species = DoublecrestedCormorant
      , id = "DoublecrestedCormorant"
      , commonName = "Double-crested Cormorant"
      , sciName = "Nannopterum auritum"
      , rate = 0.057904590874
      , pvalue = 0.0555239273
      }
    , { species = DownyWoodpecker
      , id = "DownyWoodpecker"
      , commonName = "Downy Woodpecker"
      , sciName = "Dryobates pubescens"
      , rate = -0.003474473528
      , pvalue = 0.674457061178
      }
    , { species = EasternBluebird
      , id = "EasternBluebird"
      , commonName = "Eastern Bluebird"
      , sciName = "Sialia sialis"
      , rate = -0.000477009335
      , pvalue = 0.913925509058
      }
    , { species = EasternKingbird
      , id = "EasternKingbird"
      , commonName = "Eastern Kingbird"
      , sciName = "Tyrannus tyrannus"
      , rate = -0.031928947856
      , pvalue = 0.012838237925
      }
    , { species = EasternMeadowlark
      , id = "EasternMeadowlark"
      , commonName = "Eastern Meadowlark"
      , sciName = "Sturnella magna"
      , rate = -0.025045487749
      , pvalue = 0.023767071051
      }
    , { species = EasternPhoebe
      , id = "EasternPhoebe"
      , commonName = "Eastern Phoebe"
      , sciName = "Sayornis phoebe"
      , rate = 0.006963598622
      , pvalue = 0.314270395657
      }
    , { species = EasternScreechOwl
      , id = "EasternScreechOwl"
      , commonName = "Eastern Screech-Owl"
      , sciName = "Megascops asio"
      , rate = 0.017002644589
      , pvalue = 0.766101003812
      }
    , { species = EasternTowhee
      , id = "EasternTowhee"
      , commonName = "Eastern Towhee"
      , sciName = "Pipilo erythrophthalmus"
      , rate = -0.024178061969
      , pvalue = 0.000000001367
      }
    , { species = EasternWhippoorwill
      , id = "EasternWhippoorwill"
      , commonName = "Eastern Whip-poor-will"
      , sciName = "Antrostomus vociferus"
      , rate = -0.044136400027
      , pvalue = 0.031931234974
      }
    , { species = EasternWoodPewee
      , id = "EasternWoodPewee"
      , commonName = "Eastern Wood-Pewee"
      , sciName = "Contopus virens"
      , rate = -0.005886421231
      , pvalue = 0.336774810478
      }
    , { species = EuropeanStarling
      , id = "EuropeanStarling"
      , commonName = "European Starling"
      , sciName = "Sturnus vulgaris"
      , rate = -0.024063269563
      , pvalue = 0.083975101054
      }
    , { species = FieldSparrow
      , id = "FieldSparrow"
      , commonName = "Field Sparrow"
      , sciName = "Spizella pusilla"
      , rate = -0.042085332993
      , pvalue = 0.005646759551
      }
    , { species = FishCrow
      , id = "FishCrow"
      , commonName = "Fish Crow"
      , sciName = "Corvus ossifragus"
      , rate = 0.07269737558
      , pvalue = 0.000000000003
      }
    , { species = GrasshopperSparrow
      , id = "GrasshopperSparrow"
      , commonName = "Grasshopper Sparrow"
      , sciName = "Ammodramus savannarum"
      , rate = -0.011144172857
      , pvalue = 0.657990604147
      }
    , { species = GrayCatbird
      , id = "GrayCatbird"
      , commonName = "Gray Catbird"
      , sciName = "Dumetella carolinensis"
      , rate = -0.005042490417
      , pvalue = 0.56929839549
      }
    , { species = GreatBlueHeron
      , id = "GreatBlueHeron"
      , commonName = "Great Blue Heron"
      , sciName = "Ardea herodias"
      , rate = 0.026436703823
      , pvalue = 0.009371962549
      }
    , { species = GreatCrestedFlycatcher
      , id = "GreatCrestedFlycatcher"
      , commonName = "Great Crested Flycatcher"
      , sciName = "Myiarchus crinitus"
      , rate = 0.043531164689
      , pvalue = 0.000000052348
      }
    , { species = GreatEgret
      , id = "GreatEgret"
      , commonName = "Great Egret"
      , sciName = "Ardea alba"
      , rate = -0.008258868007
      , pvalue = 0.832899804952
      }
    , { species = GreatHornedOwl
      , id = "GreatHornedOwl"
      , commonName = "Great Horned Owl"
      , sciName = "Bubo virginianus"
      , rate = -0.006571468905
      , pvalue = 0.848368652939
      }
    , { species = GreenHeron
      , id = "GreenHeron"
      , commonName = "Green Heron"
      , sciName = "Butorides virescens"
      , rate = -0.05393452343
      , pvalue = 0.006671460678
      }
    , { species = HairyWoodpecker
      , id = "HairyWoodpecker"
      , commonName = "Hairy Woodpecker"
      , sciName = "Dryobates villosus"
      , rate = -0.017943311596
      , pvalue = 0.415200961406
      }
    , { species = HoodedWarbler
      , id = "HoodedWarbler"
      , commonName = "Hooded Warbler"
      , sciName = "Setophaga citrina"
      , rate = 0.031931031707
      , pvalue = 0.00020322805
      }
    , { species = HornedLark
      , id = "HornedLark"
      , commonName = "Horned Lark"
      , sciName = "Eremophila alpestris"
      , rate = 0.039383189401
      , pvalue = 0.043590790369
      }
    , { species = HouseFinch
      , id = "HouseFinch"
      , commonName = "House Finch"
      , sciName = "Haemorhous mexicanus"
      , rate = -0.006569004141
      , pvalue = 0.42915213157
      }
    , { species = HouseSparrow
      , id = "HouseSparrow"
      , commonName = "House Sparrow"
      , sciName = "Passer domesticus"
      , rate = -0.078090790529
      , pvalue = 0.000024013845
      }
    , { species = HouseWren
      , id = "HouseWren"
      , commonName = "House Wren"
      , sciName = "Troglodytes aedon"
      , rate = -0.031677405421
      , pvalue = 0.141615572689
      }
    , { species = IndigoBunting
      , id = "IndigoBunting"
      , commonName = "Indigo Bunting"
      , sciName = "Passerina cyanea"
      , rate = -0.026546352085
      , pvalue = 0.000000599018
      }
    , { species = KentuckyWarbler
      , id = "KentuckyWarbler"
      , commonName = "Kentucky Warbler"
      , sciName = "Geothlypis formosa"
      , rate = 0.036525015791
      , pvalue = 0.315563071541
      }
    , { species = Killdeer
      , id = "Killdeer"
      , commonName = "Killdeer"
      , sciName = "Charadrius vociferus"
      , rate = -0.023458462794
      , pvalue = 0.130489702485
      }
    , { species = LoggerheadShrike
      , id = "LoggerheadShrike"
      , commonName = "Loggerhead Shrike"
      , sciName = "Lanius ludovicianus"
      , rate = -0.002519655711
      , pvalue = 0.974022421248
      }
    , { species = LouisianaWaterthrush
      , id = "LouisianaWaterthrush"
      , commonName = "Louisiana Waterthrush"
      , sciName = "Parkesia motacilla"
      , rate = 0.014623547733
      , pvalue = 0.447557726859
      }
    , { species = Mallard
      , id = "Mallard"
      , commonName = "Mallard"
      , sciName = "Anas platyrhynchos"
      , rate = -0.031708961275
      , pvalue = 0.110694028957
      }
    , { species = MourningDove
      , id = "MourningDove"
      , commonName = "Mourning Dove"
      , sciName = "Zenaida macroura"
      , rate = -0.012088340742
      , pvalue = 0.00536767389
      }
    , { species = NorthernBobwhite
      , id = "NorthernBobwhite"
      , commonName = "Northern Bobwhite"
      , sciName = "Colinus virginianus"
      , rate = -0.118477029725
      , pvalue = 0.000000000267
      }
    , { species = NorthernCardinal
      , id = "NorthernCardinal"
      , commonName = "Northern Cardinal"
      , sciName = "Cardinalis cardinalis"
      , rate = -0.001618943599
      , pvalue = 0.572430531653
      }
    , { species = NorthernFlicker
      , id = "NorthernFlicker"
      , commonName = "Northern Flicker"
      , sciName = "Colaptes auratus"
      , rate = -0.036293076271
      , pvalue = 0.02888727773
      }
    , { species = NorthernMockingbird
      , id = "NorthernMockingbird"
      , commonName = "Northern Mockingbird"
      , sciName = "Mimus polyglottos"
      , rate = -0.005462509976
      , pvalue = 0.31594040911
      }
    , { species = NorthernParula
      , id = "NorthernParula"
      , commonName = "Northern Parula"
      , sciName = "Setophaga americana"
      , rate = 0.041160534857
      , pvalue = 0.008410531067
      }
    , { species = NorthernRoughwingedSwallow
      , id = "NorthernRoughwingedSwallow"
      , commonName = "Northern Rough-winged Swallow"
      , sciName = "Stelgidopteryx serripennis"
      , rate = 0.016362536251
      , pvalue = 0.619592833683
      }
    , { species = OrchardOriole
      , id = "OrchardOriole"
      , commonName = "Orchard Oriole"
      , sciName = "Icterus spurius"
      , rate = -0.021611824999
      , pvalue = 0.103430294926
      }
    , { species = Osprey
      , id = "Osprey"
      , commonName = "Osprey"
      , sciName = "Pandion haliaetus"
      , rate = 0.063156905216
      , pvalue = 0.068765629962
      }
    , { species = Ovenbird
      , id = "Ovenbird"
      , commonName = "Ovenbird"
      , sciName = "Seiurus aurocapilla"
      , rate = -0.001010843502
      , pvalue = 0.864934872347
      }
    , { species = PileatedWoodpecker
      , id = "PileatedWoodpecker"
      , commonName = "Pileated Woodpecker"
      , sciName = "Dryocopus pileatus"
      , rate = 0.041211393861
      , pvalue = 0.013586319799
      }
    , { species = PrairieWarbler
      , id = "PrairieWarbler"
      , commonName = "Prairie Warbler"
      , sciName = "Setophaga discolor"
      , rate = -0.040117147922
      , pvalue = 0.000007843051
      }
    , { species = ProthonotaryWarbler
      , id = "ProthonotaryWarbler"
      , commonName = "Prothonotary Warbler"
      , sciName = "Protonotaria citrea"
      , rate = 0.057904590874
      , pvalue = 0.020513744563
      }
    , { species = PurpleMartin
      , id = "PurpleMartin"
      , commonName = "Purple Martin"
      , sciName = "Progne subis"
      , rate = 0.031033905749
      , pvalue = 0.000833917808
      }
    , { species = RedbelliedWoodpecker
      , id = "RedbelliedWoodpecker"
      , commonName = "Red-bellied Woodpecker"
      , sciName = "Melanerpes carolinus"
      , rate = 0.005539519614
      , pvalue = 0.18843420806
      }
    , { species = RedeyedVireo
      , id = "RedeyedVireo"
      , commonName = "Red-eyed Vireo"
      , sciName = "Vireo olivaceus"
      , rate = -0.011419111691
      , pvalue = 0.053233926322
      }
    , { species = RedheadedWoodpecker
      , id = "RedheadedWoodpecker"
      , commonName = "Red-headed Woodpecker"
      , sciName = "Melanerpes erythrocephalus"
      , rate = 0.026525997068
      , pvalue = 0.138512321937
      }
    , { species = RedshoulderedHawk
      , id = "RedshoulderedHawk"
      , commonName = "Red-shouldered Hawk"
      , sciName = "Buteo lineatus"
      , rate = 0.054622724209
      , pvalue = 0.000000122413
      }
    , { species = RedtailedHawk
      , id = "RedtailedHawk"
      , commonName = "Red-tailed Hawk"
      , sciName = "Buteo jamaicensis"
      , rate = 0.014151525569
      , pvalue = 0.441237730953
      }
    , { species = RedwingedBlackbird
      , id = "RedwingedBlackbird"
      , commonName = "Red-winged Blackbird"
      , sciName = "Agelaius phoeniceus"
      , rate = -0.041684305359
      , pvalue = 0.002638320342
      }
    , { species = RockPigeon
      , id = "RockPigeon"
      , commonName = "Rock Pigeon"
      , sciName = "Columba livia"
      , rate = -0.036342850371
      , pvalue = 0.051811952519
      }
    , { species = RubythroatedHummingbird
      , id = "RubythroatedHummingbird"
      , commonName = "Ruby-throated Hummingbird"
      , sciName = "Archilochus colubris"
      , rate = -0.030088585442
      , pvalue = 0.004459181924
      }
    , { species = ScarletTanager
      , id = "ScarletTanager"
      , commonName = "Scarlet Tanager"
      , sciName = "Piranga olivacea"
      , rate = -0.031633734264
      , pvalue = 0.000148271527
      }
    , { species = SharpshinnedHawk
      , id = "SharpshinnedHawk"
      , commonName = "Sharp-shinned Hawk"
      , sciName = "Accipiter striatus"
      , rate = -0.042686708968
      , pvalue = 0.295190730471
      }
    , { species = SongSparrow
      , id = "SongSparrow"
      , commonName = "Song Sparrow"
      , sciName = "Melospiza melodia"
      , rate = 0.039564412038
      , pvalue = 0.011213880079
      }
    , { species = SummerTanager
      , id = "SummerTanager"
      , commonName = "Summer Tanager"
      , sciName = "Piranga rubra"
      , rate = 0.029782415873
      , pvalue = 0.000038815189
      }
    , { species = TreeSwallow
      , id = "TreeSwallow"
      , commonName = "Tree Swallow"
      , sciName = "Tachycineta bicolor"
      , rate = 0.154468512258
      , pvalue = 0.007212665424
      }
    , { species = TuftedTitmouse
      , id = "TuftedTitmouse"
      , commonName = "Tufted Titmouse"
      , sciName = "Baeolophus bicolor"
      , rate = 0.005128838161
      , pvalue = 0.206059807941
      }
    , { species = TurkeyVulture
      , id = "TurkeyVulture"
      , commonName = "Turkey Vulture"
      , sciName = "Cathartes aura"
      , rate = 0.007713348765
      , pvalue = 0.689507052639
      }
    , { species = WarblingVireo
      , id = "WarblingVireo"
      , commonName = "Warbling Vireo"
      , sciName = "Vireo gilvus"
      , rate = -0.173549416385
      , pvalue = 0.049665254115
      }
    , { species = WhitebreastedNuthatch
      , id = "WhitebreastedNuthatch"
      , commonName = "White-breasted Nuthatch"
      , sciName = "Sitta carolinensis"
      , rate = 0.010414288905
      , pvalue = 0.306158604154
      }
    , { species = WhiteeyedVireo
      , id = "WhiteeyedVireo"
      , commonName = "White-eyed Vireo"
      , sciName = "Vireo griseus"
      , rate = 0.064733303035
      , pvalue = 0.000000228765
      }
    , { species = WildTurkey
      , id = "WildTurkey"
      , commonName = "Wild Turkey"
      , sciName = "Meleagris gallopavo"
      , rate = 0.084598272707
      , pvalue = 0.000284198585
      }
    , { species = WoodDuck
      , id = "WoodDuck"
      , commonName = "Wood Duck"
      , sciName = "Aix sponsa"
      , rate = 0.028359355508
      , pvalue = 0.415565838656
      }
    , { species = WoodThrush
      , id = "WoodThrush"
      , commonName = "Wood Thrush"
      , sciName = "Hylocichla mustelina"
      , rate = -0.062945957227
      , pvalue = 0.0
      }
    , { species = YellowWarbler
      , id = "YellowWarbler"
      , commonName = "Yellow Warbler"
      , sciName = "Setophaga petechia"
      , rate = 0.06731343404
      , pvalue = 0.132413101859
      }
    , { species = YellowbilledCuckoo
      , id = "YellowbilledCuckoo"
      , commonName = "Yellow-billed Cuckoo"
      , sciName = "Coccyzus americanus"
      , rate = 0.018788719374
      , pvalue = 0.007401593566
      }
    , { species = YellowbreastedChat
      , id = "YellowbreastedChat"
      , commonName = "Yellow-breasted Chat"
      , sciName = "Icteria virens"
      , rate = -0.03329204807
      , pvalue = 0.000009029872
      }
    , { species = YellowthroatedVireo
      , id = "YellowthroatedVireo"
      , commonName = "Yellow-throated Vireo"
      , sciName = "Vireo flavifrons"
      , rate = -0.01111408198
      , pvalue = 0.497440237101
      }
    , { species = YellowthroatedWarbler
      , id = "YellowthroatedWarbler"
      , commonName = "Yellow-throated Warbler"
      , sciName = "Setophaga dominica"
      , rate = 0.075058651967
      , pvalue = 0.000000000585
      }
    ]



-- Convert species to its common name as a String.


speciesToString : Species -> String
speciesToString species =
    case species of
        AcadianFlycatcher ->
            "Acadian Flycatcher"

        AmericanCrow ->
            "American Crow"

        AmericanGoldfinch ->
            "American Goldfinch"

        AmericanRedstart ->
            "American Redstart"

        AmericanRobin ->
            "American Robin"

        BaldEagle ->
            "Bald Eagle"

        BaltimoreOriole ->
            "Baltimore Oriole"

        BarnSwallow ->
            "Barn Swallow"

        BarredOwl ->
            "Barred Owl"

        BeltedKingfisher ->
            "Belted Kingfisher"

        BlackVulture ->
            "Black Vulture"

        BlackandwhiteWarbler ->
            "Black-and-white Warbler"

        BlueGrosbeak ->
            "Blue Grosbeak"

        BlueJay ->
            "Blue Jay"

        BluegrayGnatcatcher ->
            "Blue-gray Gnatcatcher"

        BlueheadedVireo ->
            "Blue-headed Vireo"

        BroadwingedHawk ->
            "Broad-winged Hawk"

        BrownThrasher ->
            "Brown Thrasher"

        BrownheadedCowbird ->
            "Brown-headed Cowbird"

        BrownheadedNuthatch ->
            "Brown-headed Nuthatch"

        CanadaGoose ->
            "Canada Goose"

        CarolinaChickadee ->
            "Carolina Chickadee"

        CarolinaWren ->
            "Carolina Wren"

        CedarWaxwing ->
            "Cedar Waxwing"

        ChimneySwift ->
            "Chimney Swift"

        Chuckwillswidow ->
            "Chuck-will's-widow"

        CliffSwallow ->
            "Cliff Swallow"

        CommonGrackle ->
            "Common Grackle"

        CommonYellowthroat ->
            "Common Yellowthroat"

        CoopersHawk ->
            "Cooper's Hawk"

        Dickcissel ->
            "Dickcissel"

        DoublecrestedCormorant ->
            "Double-crested Cormorant"

        DownyWoodpecker ->
            "Downy Woodpecker"

        EasternBluebird ->
            "Eastern Bluebird"

        EasternKingbird ->
            "Eastern Kingbird"

        EasternMeadowlark ->
            "Eastern Meadowlark"

        EasternPhoebe ->
            "Eastern Phoebe"

        EasternScreechOwl ->
            "Eastern Screech-Owl"

        EasternTowhee ->
            "Eastern Towhee"

        EasternWhippoorwill ->
            "Eastern Whip-poor-will"

        EasternWoodPewee ->
            "Eastern Wood-Pewee"

        EuropeanStarling ->
            "European Starling"

        FieldSparrow ->
            "Field Sparrow"

        FishCrow ->
            "Fish Crow"

        GrasshopperSparrow ->
            "Grasshopper Sparrow"

        GrayCatbird ->
            "Gray Catbird"

        GreatBlueHeron ->
            "Great Blue Heron"

        GreatCrestedFlycatcher ->
            "Great Crested Flycatcher"

        GreatEgret ->
            "Great Egret"

        GreatHornedOwl ->
            "Great Horned Owl"

        GreenHeron ->
            "Green Heron"

        HairyWoodpecker ->
            "Hairy Woodpecker"

        HoodedWarbler ->
            "Hooded Warbler"

        HornedLark ->
            "Horned Lark"

        HouseFinch ->
            "House Finch"

        HouseSparrow ->
            "House Sparrow"

        HouseWren ->
            "House Wren"

        IndigoBunting ->
            "Indigo Bunting"

        KentuckyWarbler ->
            "Kentucky Warbler"

        Killdeer ->
            "Killdeer"

        LoggerheadShrike ->
            "Loggerhead Shrike"

        LouisianaWaterthrush ->
            "Louisiana Waterthrush"

        Mallard ->
            "Mallard"

        MourningDove ->
            "Mourning Dove"

        NorthernBobwhite ->
            "Northern Bobwhite"

        NorthernCardinal ->
            "Northern Cardinal"

        NorthernFlicker ->
            "Northern Flicker"

        NorthernMockingbird ->
            "Northern Mockingbird"

        NorthernParula ->
            "Northern Parula"

        NorthernRoughwingedSwallow ->
            "Northern Rough-winged Swallow"

        OrchardOriole ->
            "Orchard Oriole"

        Osprey ->
            "Osprey"

        Ovenbird ->
            "Ovenbird"

        PileatedWoodpecker ->
            "Pileated Woodpecker"

        PrairieWarbler ->
            "Prairie Warbler"

        ProthonotaryWarbler ->
            "Prothonotary Warbler"

        PurpleMartin ->
            "Purple Martin"

        RedbelliedWoodpecker ->
            "Red-bellied Woodpecker"

        RedeyedVireo ->
            "Red-eyed Vireo"

        RedheadedWoodpecker ->
            "Red-headed Woodpecker"

        RedshoulderedHawk ->
            "Red-shouldered Hawk"

        RedtailedHawk ->
            "Red-tailed Hawk"

        RedwingedBlackbird ->
            "Red-winged Blackbird"

        RockPigeon ->
            "Rock Pigeon"

        RubythroatedHummingbird ->
            "Ruby-throated Hummingbird"

        ScarletTanager ->
            "Scarlet Tanager"

        SharpshinnedHawk ->
            "Sharp-shinned Hawk"

        SongSparrow ->
            "Song Sparrow"

        SummerTanager ->
            "Summer Tanager"

        TreeSwallow ->
            "Tree Swallow"

        TuftedTitmouse ->
            "Tufted Titmouse"

        TurkeyVulture ->
            "Turkey Vulture"

        WarblingVireo ->
            "Warbling Vireo"

        WhitebreastedNuthatch ->
            "White-breasted Nuthatch"

        WhiteeyedVireo ->
            "White-eyed Vireo"

        WildTurkey ->
            "Wild Turkey"

        WoodDuck ->
            "Wood Duck"

        WoodThrush ->
            "Wood Thrush"

        YellowWarbler ->
            "Yellow Warbler"

        YellowbilledCuckoo ->
            "Yellow-billed Cuckoo"

        YellowbreastedChat ->
            "Yellow-breasted Chat"

        YellowthroatedVireo ->
            "Yellow-throated Vireo"

        YellowthroatedWarbler ->
            "Yellow-throated Warbler"



-- Identify a Species by a string, maybe


stringToSpecies : String -> Maybe Species
stringToSpecies s =
    List.map (\x -> ( x, speciesToString x )) allSpecies
        |> List.filterMap
            (\( x, y ) ->
                if y == s then
                    Just x

                else
                    Nothing
            )
        |> List.head



-- Get the SpeciesRec for a Species


lookupSpecies : Species -> Maybe SpeciesRec
lookupSpecies x =
    List.filter (\r -> x == r.species) allSpeciesRec
        |> List.head
